# -*- coding: utf-8 -*-
"""v5 的 80 格規劃資料。

v4 的致命傷不是哪一格寫壞，是十六位人設共用同一套五格骨架
（私下／私下／浴室／工作／夜間外出），所以 16/16 位都有浴室格、13 位還在同一順位。
v5 先為每位人設寫「只有她會發生的五個時刻」，場域、動作、服裝、光都由事件長出來；
每位的 (私下, 工作, 房間以外) 組合刻意不同，格位順序也不同。

硬規則（validate_v5.py 執行）：
  私下 2–4 ／ 工作場域 0–1 ／ 房間以外 1–3 ／ 標誌性配額 0–1
  全批浴室 ≤6 且不得集中同一格位
  全批日 40 / 夜 40，每位 3日2夜 或 2日3夜
  全批有路人 8–12 格，且只能落在營業中／鬧區／市場／車站機場／老街
  語意矩陣（場景族·基姿·手部·視線·鏡位·光線拓撲·日夜·路人）跨人設橫排不得出現主導組合
"""

# ppl 結構：人數級別 / 距離 / 行為 / 穿著 / 面向。寫 None 就是這一格沒有人。
# light 的 li_s 必須帶 character.md 的原句摘錄，不能只寫欄位名稱。

SPECS = {}

SPECS["angel-chiu"] = dict(comp="3私1工0外→3私0工2外", rhythm="3日2夜", slots=[
 dict(id="A1", ev="大夜下班進門第一件事是洗澡，洗完才想到還沒吃東西",
      pil="浴室 / 晨間", wt="20%", flag=None, fam="浴室", pose="站", hand="整理頭髮",
      gaze="看鏡頭", view="selfie", topo="單一光源正前", time="night", ppl=None,
      pl="她租屋處的浴室，剛洗完澡，鏡子上還有水氣",
      pl_en="in the bathroom of her rented flat, straight out of a shower after a night shift, water still beading on the mirror",
      ac="她把濕頭髮撥到一邊，漂過的髮尾顏色這時候才看得出來",
      ac_en="She has pushed her wet hair over to one side, and the lightened ends show properly for the first time all day.",
      ac_s="小習慣：下班第一件事一定是洗澡／髮尾漂過的顏色只有下班才看得到",
      of="米灰色浴巾裹著，肩線與鎖骨露在外面",
      of_en="a soft grey bath towel wrapped around her, her shoulders and collarbones bare above it",
      of_s="色盤：米灰",
      li="鏡子上方那盞暖燈在她正前方，浴室深處落入暗，畫面保留顆粒",
      li_en="The warm strip light above the mirror is directly in front of her, the far end of the bathroom falls away into dark, and the grain is left in the picture.",
      li_s="後製原句：「暖光場景保留顆粒與陰影」／氛圍原句：「租屋處的暖」",
      fa="剛洗完的鬆，眼睛看著鏡頭，沒有笑",
      fa_en="Loose and just-washed, looking straight into the lens without smiling.",
      fa_s="語氣：平實、不解釋、不撒嬌",
      hair_en="wet and pushed over one shoulder, the lightened honey-tea ends darkened by the water"),
 dict(id="A2", ev="洗完澡坐在床邊，才發現自己整個人跟上班時完全不一樣——她的帳號就是從這一刻開始的",
      pil="私下 / 房間裡的她", wt="30%", flag=None, fam="臥室", pose="坐床沿", hand="空手",
      gaze="看側邊", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="她租屋處的床邊，窗簾拉著，外面天其實已經亮了",
      pl_en="on the edge of the bed in her rented room, the curtains drawn even though it is already getting light outside",
      ac="她一條腿收上床，人往後靠在手上，像是還沒決定要不要睡",
      ac_en="One leg is drawn up onto the bed and she is leaning back on one hand, as if she has not decided yet whether to sleep.",
      ac_s="誰是她：大夜下班回租屋處，洗完澡坐在床邊",
      of="裸粉色絲質睡裙，肩帶滑到手臂上",
      of_en="a nude-pink silk nightdress with one strap slipped down onto her arm",
      of_s="私下核心：換上絲質睡裙／色盤：裸粉",
      li="床頭一盞暖黃燈從她側前方來，房間其餘部分暗",
      li_en="One warm bedside lamp reaches her from the side and in front, and the rest of the room stays dark.",
      li_s="私下核心原句：「房間暖黃光、床邊、鏡子」",
      fa="剛下大夜的疲態沒有遮，視線落在窗簾那一側",
      fa_en="The tiredness of a finished night shift is not hidden, and her eyes are on the curtained side of the room.",
      fa_s="幽默：常拿輪班和睡眠不足自嘲",
      hair_en="down and half-dry, the honey-tea ends showing"),
 dict(id="A3", ev="補完眠下午出門，繞去巷子裡那間開了很久的早餐店買東西",
      pil="外出 / 休假", wt="10%", flag="房間以外", fam="街道", pose="站", hand="單手持物",
      gaze="看側邊", view="full", topo="環境均勻", time="day", ppl=None,
      pl="台北巷子裡一間開了很久的早餐店門口，下午，鐵捲門拉了一半",
      pl_en="outside a long-established breakfast shop in a Taipei back lane in the afternoon, its roller shutter already half down",
      ac="她一手提著塑膠袋，另一手插在口袋裡，人剛從店裡走出來",
      ac_en="She has a plastic carrier bag in one hand and the other hand in her pocket, having just come out of the shop.",
      ac_s="小習慣：下班第一件事一定是洗澡，第二件才是吃東西",
      of="深藍色短版針織上衣配米灰色長褲",
      of_en="a navy cropped knit top with wide grey-beige trousers",
      of_s="色盤：深藍、米灰",
      li="下午的天光是平的，巷子兩側的牆把光壓下來一點",
      li_en="The afternoon daylight is flat and open, dimmed a little by the walls on both sides of the lane.",
      li_s="氛圍原句：「醫院日光燈的冷 vs 租屋處的暖」——這一格兩種都不是，用平的天光",
      fa="沒睡飽但心情不壞，看向巷子的另一頭",
      fa_en="Short on sleep but in no bad mood, looking off down the other end of the lane.",
      fa_s="語氣：平實、簡短",
      hair_en="tied back loosely, the lightened ends gathered at the nape"),
 dict(id="A4", ev="翻衣櫃找明天要穿的，刷手服就掛在同一根桿子上",
      pil="穿搭 / 換裝", wt="20%", flag=None, fam="衣櫃 / 更衣", pose="站", hand="單手扶物",
      gaze="看手上的東西", view="knee", topo="單一光源側前", time="day", ppl=None,
      pl="她房間的開放式衣架前，刷手服和便服掛在同一根桿子上",
      pl_en="at the open clothes rail in her room, where her scrubs hang on the same rail as everything else she owns",
      ac="她一手把一件衣服拉出來比在身前，另一手還撐著衣架",
      ac_en="She has pulled one piece out and is holding it up against herself, her other hand still steadying the rail.",
      ac_s="小習慣：很少發文講工作內容，但常常出現制服的一角",
      of="白色棉質背心配家居短褲",
      of_en="a white cotton vest with soft home shorts",
      of_s="色盤：冷白",
      li="窗光從側面進來，衣架那一側亮、房間另一側暗",
      li_en="Window light comes in from the side, bright along the rail and darker across the rest of the room.",
      li_s="氛圍原句：「兩種光是她整個帳號的骨架」——這一格用日光那一側",
      fa="專心在衣服上，沒有在看鏡頭",
      fa_en="Concentrating on the clothes, not looking at the lens at all.",
      fa_s="性格：對事情有條理，護理工作養出來的",
      hair_en="twisted up into a quick clip with loose strands down"),
 dict(id="A5", ev="休假日走去傳統市場，那個時間攤子都還在",
      pil="外出 / 休假", wt="10%", flag="房間以外", fam="市場", pose="走動", hand="單手持物",
      gaze="看側邊", view="knee", topo="環境均勻", time="day",
      ppl=dict(level="數人", dist="中", act="在攤子前挑東西、跟攤商講話",
               wear="輕便的家常衣服、拖鞋、提著購物袋，市場早上該有的樣子",
               facing="背對或側對鏡頭"),
      pl="台北一個傳統市場的走道，上午，兩側攤子都開著",
      pl_en="in the aisle of a traditional Taipei market in the morning, stalls open on both sides",
      ac="她拎著一袋東西從攤子之間走過去，正要轉頭看右邊那攤",
      ac_en="She is walking between the stalls with a bag in one hand, turning her head to look at the one on her right.",
      ac_s="小習慣：下班第二件事才是吃東西",
      of="淺色短袖襯衫外搭，裡面是貼身背心，配牛仔長褲",
      of_en="a light open shirt over a fitted vest, with jeans",
      of_s="色盤：冷白、米灰",
      li="市場頂棚把上午的光濾成均勻的散射光",
      li_en="The market canopy filters the morning light into an even, diffuse wash over the whole aisle.",
      li_s="氛圍：日光那一側；市場不是她的暖光租屋處，所以不用單一光源",
      fa="很自然的日常表情，沒有對鏡頭",
      fa_en="An ordinary everyday expression, not directed at the camera.",
      fa_s="語氣：講話像在交班",
      hair_en="in a low ponytail"),
])

SPECS["angeline-kwee"] = dict(comp="2私1工2外", rhythm="3日2夜", slots=[
 dict(id="G1", ev="店裡有客人在看架上的東西，她站在一旁沒有上前推銷",
      pil="選物店工作", wt="25%", flag="唯一的工作場域", fam="店內", pose="倚牆", hand="空手",
      gaze="看側邊", view="knee", topo="窗光側面", time="day",
      ppl=dict(level="1-2人", dist="中", act="在柚木層架前拿起東西看",
               wear="雅加達南區逛選物店會穿的輕便衣服", facing="背對鏡頭"),
      pl="她在南雅加達那間很小的選物店裡，營業時間，白牆與柚木層架",
      pl_en="inside her very small select shop in South Jakarta during opening hours, white walls and teak shelving",
      ac="她靠在櫃檯邊上，兩手都空著，把店留給客人自己看",
      ac_en="She is leaning against the end of the counter with both hands free, leaving the customer to look on their own.",
      ac_s="誰是她：招呼熟客，是她自己想做的事／語氣：平穩、有禮、不炫耀",
      of="白色亞麻長裙配同色系無袖上衣",
      of_en="a white linen skirt with a matching sleeveless top",
      of_s="色盤：白、暖石灰",
      li="店門的自然光從側面進來，層架深處比較暗",
      li_en="Daylight from the shop front comes in from the side, and it is darker back among the shelves.",
      li_s="後製原句：「自然光為主、暖中性色調」",
      fa="很淡的表情，看著客人那一側",
      fa_en="A very mild expression, watching in the customer's direction.",
      fa_s="幽默：淡淡的，常常自嘲自己的店很小",
      hair_en="down and straight, tucked behind one ear"),
 dict(id="G2", ev="打烊回公寓，落地窗沒有窗簾，外面的燈就是房間的燈",
      pil="私下 / 市中心公寓", wt="30%", flag=None, fam="客廳", pose="站", hand="單手扶物",
      gaze="看側邊", view="near", topo="背光", time="night", ppl=None,
      pl="她市中心公寓的落地窗前，整片窗上完全沒有窗簾",
      pl_en="at the floor-to-ceiling window of her city-centre apartment, which has no curtains on it at all",
      ac="她一手撐在窗框上，身體側過去看外面",
      ac_en="One hand rests against the window frame as she turns side-on to look out.",
      ac_s="小習慣：公寓的落地窗從不裝窗簾",
      of="淡綠色絲質吊帶裙",
      of_en="a pale green silk slip dress on thin straps",
      of_s="私下核心：絲質吊帶裙／色盤：淡綠",
      li="外面的城市燈光在她身後，室內沒開燈，她的輪廓被窗光描出來",
      li_en="The city lights are behind her and nothing indoors is switched on, so the window light draws her outline.",
      li_s="氛圍原句：「雅加達的都會室內光為主…乾淨、溫暖、不喧鬧」",
      fa="剛洗完澡的鬆，沒有在看鏡頭",
      fa_en="Loose and freshly showered, not looking at the lens.",
      fa_s="私下核心：剛洗完澡的長髮",
      hair_en="long and damp, falling down her back"),
 dict(id="G3", ev="新到的貨她一定自己先用一週，這週是這個",
      pil="穿搭 / 選貨", wt="20%", flag=None, fam="客廳", pose="坐椅", hand="單手持物",
      gaze="看手上的東西", view="knee", topo="窗光側面", time="day", ppl=None,
      pl="她公寓的柚木矮櫃旁，新到的貨拆開放在櫃面上",
      pl_en="beside the teak low cabinet in her apartment, this week's new stock unpacked across the top of it",
      ac="她坐在矮櫃旁的椅子上，把其中一件拿在手裡翻看",
      ac_en="She is sitting in the chair beside the cabinet, turning one of the pieces over in her hand.",
      ac_s="小習慣：新貨到一定自己先用一週",
      of="藤編米色的居家長洋裝",
      of_en="a long rattan-beige house dress",
      of_s="色盤：藤編米",
      li="上午的窗光從左邊進來，柚木把光吃成暖色",
      li_en="Morning window light comes in from the left, and the teak warms it as it lands.",
      li_s="氛圍原句：「白牆、柚木、藤編、棕櫚陰影」",
      fa="專注，嘴角沒有動",
      fa_en="Focused, with no movement at the corners of her mouth.",
      fa_s="語氣：句子不長",
      hair_en="pinned up loosely with a few strands escaping"),
 dict(id="G4", ev="下午約在一間老房子改的咖啡店，棕櫚的影子打在牆上",
      pil="旅遊 / 度假期", wt="10%", flag="房間以外", fam="店內", pose="坐椅", hand="雙手持物",
      gaze="看鏡頭", view="near", topo="窗光側面", time="day", ppl=None,
      pl="南雅加達一間老房子改的咖啡店，午後，棕櫚的影子落在白牆上",
      pl_en="in a South Jakarta coffee shop converted from an old house in the afternoon, palm shadows falling across the white wall",
      ac="她兩手捧著杯子放在桌上，身體微微前傾",
      ac_en="Both hands are around the cup on the table and she is leaning very slightly forward.",
      ac_s="性格：平穩、有禮",
      of="白色削肩上衣配淡綠色長褲",
      of_en="a white off-shoulder top with pale green trousers",
      of_s="色盤：白、淡綠",
      li="午後的自然光從窗那一側過來，棕櫚影子在牆上動",
      li_en="Afternoon daylight comes from the window side, and the palm shadows shift on the wall behind her.",
      li_s="氛圍原句：「棕櫚陰影。乾淨、溫暖、不喧鬧」",
      fa="很輕的笑，眼睛看著鏡頭",
      fa_en="A very light smile, her eyes on the lens.",
      fa_s="語氣：平穩、有禮、不炫耀",
      hair_en="down in soft waves"),
 dict(id="G5", ev="晚上走回公寓，那條街上的店還開著",
      pil="旅遊 / 度假期", wt="10%", flag="房間以外", fam="街道", pose="走動", hand="空手",
      gaze="看側邊", view="full", topo="環境均勻", time="night", ppl=None,
      pl="南雅加達一條晚上還開著幾間店的街，剛下過雨，地是濕的",
      pl_en="on a South Jakarta street where a few shops are still open at night, the ground wet from earlier rain",
      ac="她一個人慢慢走回去，手沒有拿東西",
      ac_en="She is walking back slowly on her own with nothing in her hands.",
      ac_s="誰是她：關門之後的公寓",
      of="暖石灰色的長版襯衫洋裝",
      of_en="a long warm-stone-grey shirt dress",
      of_s="色盤：暖石灰",
      li="店面招牌的光落在人行道上，街的另一側暗",
      li_en="Light from the shopfront signs falls across the pavement, and the other side of the street stays dark.",
      li_s="氛圍原句：「都會室內光為主…不喧鬧」——夜街用店面的光而不是路燈",
      fa="安靜，看著前面",
      fa_en="Quiet, looking ahead of her.",
      fa_s="語氣：平穩",
      hair_en="down and slightly windblown"),
])

SPECS["cheryl-soh"] = dict(comp="3私1工1外", rhythm="2日3夜", slots=[
 dict(id="C1", ev="清晨到樟宜準備出勤，航廈已經有旅客了",
      pil="制服 / 出勤", wt="20%", flag="唯一的工作場域", fam="車站機場", pose="走動", hand="單手持物",
      gaze="看側邊", view="full", topo="環境均勻", time="day",
      ppl=dict(level="數人", dist="遠", act="拖著行李走向登機門、在座位區等",
               wear="旅客的衣服，外套、帽 T、拖著行李箱", facing="背對鏡頭"),
      pl="樟宜機場的航廈走道，清晨，玻璃外停著一架飛機",
      pl_en="in a Changi terminal walkway in the early morning, an aircraft parked outside the glass",
      ac="她拉著行李箱走過去，另一手把包的帶子往肩上撥",
      ac_en="She is walking through pulling her cabin case, her other hand pushing the bag strap back up her shoulder.",
      ac_s="誰是她：制服與時差／小習慣：落地第一件事是把包頭放下來（此刻還沒放）",
      of="深藍色空服制服套裝，裙長及膝",
      of_en="a navy cabin-crew uniform suit with a knee-length skirt",
      of_s="標誌性配額以外的正規制服／色盤：深藍",
      li="航廈的冷白照明加上玻璃外的清晨天光，整體是冷的",
      li_en="The terminal's cool white lighting mixes with early daylight through the glass, and the whole scene reads cold.",
      li_s="後製原句：「冷調的出勤場景」／氛圍原句：「機場冷光與飯店暖光的兩地切換」",
      fa="上班的臉，禮貌但有距離",
      fa_en="Her working face: polite and at a distance.",
      fa_s="氛圍原句：「乾淨、有距離的高級感」",
      hair_en="in a tight low chignon"),
 dict(id="C2", ev="落地進飯店房間，第一件事是把包頭放下來，再點那款蠟燭",
      pil="飯店 / 各國城市", wt="15%", flag=None, fam="臥室", pose="坐床沿", hand="整理頭髮",
      gaze="垂眼", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="一間剛落地的飯店房間，窗簾已經被她拉開，行李攤在地上",
      pl_en="in a hotel room she has just landed into, the curtains already pulled open by her and the case lying open on the floor",
      ac="她坐在床沿把髮夾一根一根拆下來，包頭鬆開一半",
      ac_en="She is sitting on the edge of the bed taking the pins out one at a time, the chignon already half undone.",
      ac_s="小習慣：落地第一件事是把包頭放下來／飯店房間一定先拉開窗簾",
      of="制服襯衫還穿著，扣子解開兩顆，裙子換成了飯店的浴袍下襬",
      of_en="still in her uniform shirt with the top two buttons undone, the skirt already swapped for hotel-robe fabric below",
      of_s="私下核心：制服脫下後的房間",
      li="床頭一盞飯店的暖黃燈在她側前方，房間其餘部分暗",
      li_en="One warm hotel bedside lamp sits to the side and in front of her, and the rest of the room is dark.",
      li_s="氛圍原句：「飯店暖光」／後製原句：「暖調的房間場景」",
      fa="時差還在臉上，眼睛往下看著手上的夾子",
      fa_en="The time difference is still on her face and her eyes are down on the pins in her hand.",
      fa_s="幽默：乾式的、跟時差和行李有關的自嘲",
      hair_en="a chignon halfway taken down, loose sections falling"),
 dict(id="C3", ev="回新加坡的家，時差還沒調回來，凌晨三點還醒著",
      pil="私下 / 一個人的房間", wt="30%", flag=None, fam="臥室", pose="半躺", hand="空手",
      gaze="看鏡頭", view="floor", topo="單一光源正前", time="night", ppl=None,
      pl="她新加坡公寓的床上，凌晨三點，整間房只有一盞燈",
      pl_en="across the bed in her Singapore apartment at three in the morning, one lamp on in the whole flat",
      ac="她橫躺在床上，一隻手臂枕在頭下面，另一隻放在身側",
      ac_en="She is lying across the bed with one arm tucked under her head and the other resting at her side.",
      ac_s="私下核心：她的性感由「一個人的房間 + 時差」構成，安靜而私密",
      of="白色絲質睡衣兩件式",
      of_en="a two-piece white silk sleep set",
      of_s="私下核心：絲質睡衣／色盤：白",
      li="那盞燈在她正前方低處，床的另一半落在暗裡",
      li_en="The lamp is low and directly in front of her, and the far half of the bed falls into shadow.",
      li_s="後製原句：「暖調的房間場景。維持清晰高質感」",
      fa="完全醒著但很平靜，看著鏡頭",
      fa_en="Completely awake but calm, looking at the lens.",
      fa_s="語氣：私下的貼文很短",
      hair_en="down and slightly messy from the pillow"),
 dict(id="C4", ev="在家的日子完全不化妝，這天早上也是",
      pil="浴室 / 晨間", wt="15%", flag=None, fam="浴室", pose="站", hand="單手扶物",
      gaze="看鏡頭", view="selfie", topo="窗光側面", time="day", ppl=None,
      pl="她新加坡公寓的浴室，早上，檯面上只有一瓶卸妝和那款蠟燭",
      pl_en="in the bathroom of her Singapore apartment in the morning, only a bottle of cleanser and that same candle on the counter",
      ac="她一手撐著洗手台邊緣，身體微微側著",
      ac_en="One hand rests on the edge of the basin and her body is turned very slightly to the side.",
      ac_s="小習慣：在家的日子完全不化妝／行李裡永遠有同一款蠟燭",
      of="白色棉質背心配低腰短褲",
      of_en="a white cotton vest with low-slung shorts",
      of_s="色盤：白",
      li="高窗的日光從側面進來，浴室是亮的，不是單一燈源",
      li_en="Daylight from a high window comes in from the side and the bathroom is bright throughout, not lit by a single lamp.",
      li_s="後製原句：「維持清晰高質感，膚色白皙」——在家的白天不套用出勤的冷調",
      fa="完全素顏，很直接地看著鏡頭",
      fa_en="Completely without makeup, looking very directly at the lens.",
      fa_s="語氣：英文為主、簡潔有禮",
      hair_en="down and unstyled"),
 dict(id="C5", ev="在東京那一晚不想待在房間，出去走了一段還開著的街",
      pil="飯店 / 各國城市", wt="15%", flag="房間以外", fam="街道", pose="站", hand="空手",
      gaze="看側邊", view="knee", topo="環境均勻", time="night", ppl=None,
      pl="東京一條晚上還開著幾間小店的街，招牌的光落在路面上",
      pl_en="on a Tokyo street where a few small places are still open at night, sign light falling across the road surface",
      ac="她站在店與店之間停了一下，兩手都空著",
      ac_en="She has stopped for a moment between two shopfronts, both hands empty.",
      ac_s="誰是她：帳號一開始只是記錄各個城市",
      of="冷灰色長大衣，裡面是深色的貼身洋裝",
      of_en="a long cool-grey coat over a dark fitted dress",
      of_s="色盤：冷灰",
      li="招牌與店面的光從兩側來，街道深處暗",
      li_en="Sign and shopfront light reaches her from both sides, and the street runs dark further down.",
      li_s="氛圍原句：「乾淨、有距離的高級感」",
      fa="安靜，看著街的另一側",
      fa_en="Quiet, looking across to the other side of the street.",
      fa_s="語氣：簡潔有禮",
      hair_en="down, out of the chignon, with a kink where it was pinned"),
])

SPECS["emma-kao"] = dict(comp="2私1工2外", rhythm="2日3夜", slots=[
 dict(id="E1", ev="晚間新聞收播，棚裡其他燈都關了，只剩主播桌上那一盞",
      pil="職業 / 棚內檯面", wt="20%", flag="唯一的工作場域", fam="工作場域", pose="坐椅", hand="單手持物",
      gaze="看側邊", view="near", topo="單一光源正前", time="night", ppl=None,
      pl="台南地方台的新聞棚，收播後，棚內其他燈已經關了",
      pl_en="at the news desk of a local Tainan station after the broadcast has ended, every other light in the studio already switched off",
      ac="她還坐在主播桌後面，手上拿著剛剛那疊稿子，人已經鬆下來",
      ac_en="She is still behind the desk with the script she has just read in her hand, already gone slack in the chair.",
      ac_s="小習慣：下播後西裝外套一定先掛好，其他的才隨便（外套還在椅背上）",
      of="主播西裝外套已經脫在椅背，白襯衫只扣了兩顆",
      of_en="her suit jacket already off over the back of the chair, her white shirt buttoned only twice",
      of_s="私下核心：襯衫只扣兩顆／標誌性配額是「私下改造版」，這一格不是",
      li="主播桌上方那一盞燈還亮著，棚內其餘部分全黑",
      li_en="The one light above the desk is still on and the rest of the studio is completely black.",
      li_s="後製原句：「乾淨、對稱感強的棚內」——但收播後只剩一盞，對稱被打破",
      fa="播報的臉已經卸掉了，看向棚的另一邊",
      fa_en="The broadcast face is already off, and she is looking over to the other side of the studio.",
      fa_s="幽默：用播報腔講很日常的事",
      hair_en="still set for broadcast, the wine-red section showing at one side"),
 dict(id="E2", ev="回到老公寓，第一件事是把西裝外套掛好，然後才去拿梳妝台第一格的挑染片",
      pil="私下 / 下播之後", wt="30%", flag=None, fam="臥室", pose="坐椅", hand="整理頭髮",
      gaze="垂眼", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="台南老公寓的梳妝台前，第一格抽屜是開著的",
      pl_en="at the dressing table in her old Tainan apartment, the first drawer pulled open",
      ac="她把酒紅色的挑染片夾上去，動作很熟",
      ac_en="She is clipping the wine-red hair piece in, her hands doing it without needing to look.",
      ac_s="小習慣：私下才夾的酒紅挑染片放在梳妝台第一格",
      of="白襯衫還穿著，黑絲和高跟鞋都沒換",
      of_en="still in the white shirt, still in black stockings and heels she has not changed out of",
      of_s="私下核心：襯衫只扣兩顆、黑絲、高跟鞋留著沒換",
      li="梳妝台的檯燈是唯一的光，從她側前方來，房間其餘部分全暗",
      li_en="The dressing-table lamp is the only light, reaching her from the side and in front, the rest of the room completely dark.",
      li_s="後製原句：「私下場景刻意破壞構圖，用單一光源與陰影」",
      fa="眼睛往下看著手上的髮片，嘴角有一點",
      fa_en="Her eyes are down on the hair piece in her hand and there is something at the corner of her mouth.",
      fa_s="私下核心：她享受這個只有自己知道的落差",
      hair_en="dark brown, the wine-red section being clipped in at one side"),
 dict(id="E3", ev="白天翻那一整櫃只在鏡頭前穿的衣服，找下一集要穿的",
      pil="穿搭", wt="20%", flag=None, fam="衣櫃 / 更衣", pose="站", hand="單手扶物",
      gaze="看手上的東西", view="knee", topo="窗光側面", time="day", ppl=None,
      pl="老公寓的衣櫃前，整櫃都是只在鏡頭前穿的衣服",
      pl_en="in front of the open wardrobe in her old apartment, a whole rail of clothes she only ever wears on camera",
      ac="她把一件外套拉出來看肩線，另一手還扶著衣櫃門",
      ac_en="She has pulled one jacket out to check how the shoulder sits, her other hand still on the wardrobe door.",
      ac_s="小習慣：家裡有一整櫃只在鏡頭前穿的衣服",
      of="米白色家居長裙",
      of_en="an off-white long house skirt with a fitted top",
      of_s="色盤：米白",
      li="白天的窗光從側面進來，衣櫃內側暗",
      li_en="Daylight comes in from the side and it stays dark inside the wardrobe.",
      li_s="後製原句：「私下場景刻意破壞構圖」——白天也不用對稱構圖",
      fa="很專業地在評估一件衣服",
      fa_en="Assessing the jacket quite professionally.",
      fa_s="性格：她的工作是每天把自己整理成一個可信的樣子",
      hair_en="down and unstyled, no hair piece in"),
 dict(id="E4", ev="睡不著，上頂樓吹風，洗衣繩上還晾著東西",
      pil="私下 / 下播之後", wt="30%", flag="房間以外", fam="陽台 / 頂樓", pose="倚牆", hand="空手",
      gaze="看側邊", view="knee", topo="背光", time="night", ppl=None,
      pl="老公寓的頂樓，夜裡，一條洗衣繩還橫在那裡",
      pl_en="up on the roof of her old apartment building at night, a washing line still strung across it",
      ac="她靠在女兒牆上，讓風把襯衫吹起來一點",
      ac_en="She is leaning back against the parapet, letting the wind lift the shirt a little.",
      ac_s="私下核心原句：頂樓夜風",
      of="墨綠色長版襯衫外套，裡面是貼身的",
      of_en="a dark green long shirt worn open over something fitted",
      of_s="色盤：墨綠",
      li="城市的燈在她身後比較亮，頂樓本身沒有光源",
      li_en="The city glow behind her is the brighter thing; the roof itself has no light of its own.",
      li_s="氛圍原句：「棚內的紀律感 vs 老公寓的鬆散」",
      fa="放空，看著遠處",
      fa_en="Emptied out, looking off into the distance.",
      fa_s="語氣：私下的貼文反而很短",
      hair_en="down and moving in the wind, the wine-red section visible"),
 dict(id="E5", ev="出差到別的城市，白天有兩個小時是自己的",
      pil="旅遊 / 出差", wt="15%", flag="房間以外", fam="園林 / 戶外自然", pose="倚牆", hand="單手持物",
      gaze="看側邊", view="full", topo="背光", time="day", ppl=None,
      pl="出差那個城市的舊城河堤，白天，對岸是低矮的老房子，堤上這一段沒有別人",
      pl_en="on the old riverside embankment of the city she is working in, low old houses on the far bank, this stretch of it empty",
      ac="她靠在堤邊的欄杆上，一手拿著飲料，看著對岸",
      ac_en="She is leaning on the rail at the edge of the embankment with a drink in one hand, looking across to the far bank.",
      ac_s="性格：帳號是她想有一個地方可以不用字正腔圓",
      of="暖木色系的長洋裝配平底鞋",
      of_en="a long dress in warm wood tones with flat shoes",
      of_s="色盤：暖木",
      li="太陽在對岸那一側，光從她背後過來，河面反著亮",
      li_en="The sun is over on the far bank so the light comes from behind her, and the river surface is the brightest thing in the frame.",
      li_s="後製：私下場景用單一光源——這一格是外出，所以不套用",
      fa="很鬆的表情，完全不是播報的臉，眼睛看著對岸",
      fa_en="A very loose expression, nothing like the broadcast face, her eyes on the far bank.",
      fa_s="誰是她：落差本身就是最有力的內容",
      hair_en="tied up off her neck"),
])

SPECS["jia-seo"] = dict(comp="2私1工2外", rhythm="3日2夜", slots=[
 dict(id="J1", ev="白天在家的全身鏡前看膝蓋，冰敷袋就放在旁邊",
      pil="私下 / 收工後的鏡子前", wt="30%", flag=None, fam="客廳", pose="坐地", hand="單手扶物",
      gaze="看側邊", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="她家客廳角落的全身鏡前，白天，冰敷袋擱在地板上",
      pl_en="on the floor in front of the full-length mirror in the corner of her living room in the daytime, an ice pack lying beside her",
      ac="她坐在地板上，一手按著膝蓋，另一手撐在身後",
      ac_en="She is sitting on the floor with one hand pressed to her knee and the other braced behind her.",
      ac_s="小習慣：冰敷袋是隨身物品／幽默：最常吐槽自己的膝蓋",
      of="灰色運動內衣配同色低腰長褲",
      of_en="a grey sports bra with matching low-rise leggings",
      of_s="私下核心：運動內衣 + 低腰褲／色盤：灰",
      li="大面窗的日光從側面進來，房間另一側暗",
      li_en="Daylight from the big window comes in from the side, and the far side of the room is darker.",
      li_s="氛圍原句：「練舞室的白日光燈…vs 家裡的暖光」——這一格是家裡的白天",
      fa="皺了一下眉，看著膝蓋那邊",
      fa_en="A brief frown, her eyes on the knee.",
      fa_s="語氣：直接、句子短",
      hair_en="in a high ponytail, the mint-green under-layer showing where it swings"),
 dict(id="J2", ev="練完之後洗澡，那是她一天真正結束的點",
      pil="浴室 / 晨間", wt="15%", flag=None, fam="浴室", pose="站", hand="整理頭髮",
      gaze="看鏡頭", view="selfie", topo="單一光源正前", time="day", ppl=None,
      pl="她家的浴室，剛練完澡，鏡子上有一層水氣",
      pl_en="in her own bathroom straight after a shower following practice, a film of steam across the mirror",
      ac="她兩手把濕頭髮往後攏，薄荷綠那一層這時候露出來",
      ac_en="She is gathering her wet hair back with both hands, and the mint-green under-layer shows as she does it.",
      ac_s="小習慣：薄荷綠那層頭髮只有甩起來才看得到",
      of="黑色運動內衣還沒換掉，下面是浴巾",
      of_en="still in the black sports bra with a towel below it",
      of_s="色盤：黑",
      li="鏡上那盞燈在她正前方，浴室深處被水氣吃掉",
      li_en="The strip light above the mirror is directly in front of her and the far end of the bathroom is swallowed by the steam.",
      li_s="後製原句：「私下場景改用單一暖光與淺景深」",
      fa="剛練完的紅，看著鏡頭，沒有笑",
      fa_en="Still flushed from practice, looking at the lens without smiling.",
      fa_s="語氣：直接、有節拍感",
      hair_en="wet and being pulled straight back, mint-green under-layer exposed"),
 dict(id="J3", ev="學生都走了，她把大燈關掉自己再跑一次",
      pil="練舞室 / 跳舞", wt="25%", flag="唯一的工作場域", fam="工作場域", pose="站", hand="空手",
      gaze="看側邊", view="full", topo="單一光源側前", time="night", ppl=None,
      pl="江南那間練舞室，收工後關了大燈，只剩鏡子旁的一盞，木地板",
      pl_en="in the Gangnam dance studio after hours, the main lights off and only the one beside the mirror left on, wooden floor",
      ac="她停在一個動作的中間，重心壓在一腳上，兩手都甩開",
      ac_en="She has stopped in the middle of a move, her weight down on one leg and both arms thrown out.",
      ac_s="私下核心：練舞室關燈後的鏡子前",
      of="黑色露腰舞衣配低腰寬褲",
      of_en="a black cropped dance top with low-slung wide trousers",
      of_s="標誌性配額：露腰舞衣 / 汗",
      li="鏡子旁那一盞燈在她側前方，練舞室深處全暗",
      li_en="The single lamp beside the mirror is to one side and in front of her, and the far end of the studio is completely dark.",
      li_s="後製原句：「高清晰度的舞蹈素材（動態需要）」",
      fa="喘著，眼睛看向鏡子那一側",
      fa_en="Out of breath, her eyes towards the mirror side of the room.",
      fa_s="語氣：有節拍感",
      hair_en="high ponytail coming loose, strands stuck to her neck"),
 dict(id="J4", ev="教完最後一堂走出來，便利商店外面的座位還有人",
      pil="外出 / 江南", wt="15%", flag="房間以外", fam="街道", pose="坐椅", hand="單手持物",
      gaze="看鏡頭", view="knee", topo="環境均勻", time="night", ppl=None,
      pl="江南一間便利商店外面的座位，深夜，剛教完課",
      pl_en="at the outdoor seating of a Gangnam convenience store late at night, straight after teaching",
      ac="她坐在塑膠椅上，一手拿著飲料，另一手垂在腿上",
      ac_en="She is sitting on the plastic chair with a drink in one hand and the other hanging over her thigh.",
      ac_s="誰是她：現在是那裡最多學生的老師之一",
      of="寬版連帽外套罩在舞衣外面，下面還是那條低腰褲",
      of_en="an oversized hooded jacket thrown over the dance top, still in the same low-rise trousers",
      of_s="色盤：冷白、黑",
      li="便利商店的白光從店裡打出來，座位區以外都暗",
      li_en="White light spills out of the store across the seating, and everything beyond it is dark.",
      li_s="氛圍：這一格不用家裡的暖光，也不用練舞室的日光燈",
      fa="累到笑不出來，但看著鏡頭",
      fa_en="Too tired to smile, but looking at the lens.",
      fa_s="幽默：毒舌但溫暖",
      hair_en="ponytail pulled out, hair down and flat"),
 dict(id="J5", ev="白天在江南街上，她那身穿搭比舞蹈影片還多人看",
      pil="穿搭", wt="15%", flag="房間以外", fam="街道", pose="站", hand="空手",
      gaze="看鏡頭", view="full", topo="環境均勻", time="day", ppl=None,
      pl="江南一條白天的街，商業大樓的玻璃在她身後",
      pl_en="on a Gangnam street in the daytime, office glass behind her",
      ac="她站在路邊等人，重心壓在一腳，兩手都空著",
      ac_en="She is standing at the kerb waiting for someone, her weight on one leg and both hands empty.",
      ac_s="誰是她：帳號一開始只放 cover dance，後來她開始放自己",
      of="白色露腰短上衣配寬鬆低腰牛仔褲",
      of_en="a white cropped top with loose low-rise jeans",
      of_s="色盤：冷白／標誌性配額以外的日常露腰",
      li="白天的天光是平的，大樓玻璃反回來一點",
      li_en="The daylight is flat and the office glass throws a little of it back.",
      li_s="後製：這一格不是私下場景，所以不用單一暖光",
      fa="沒有表情，很直接地看著鏡頭",
      fa_en="No particular expression, looking very directly at the lens.",
      fa_s="語氣：直接",
      hair_en="down and straight, mint-green under-layer just visible"),
])

SPECS["miu-shiraishi"] = dict(comp="2私1工2外", rhythm="2日3夜", slots=[
 dict(id="M1", ev="營業中，有人為了看她做咖啡在排隊",
      pil="咖啡店工作", wt="20%", flag="唯一的工作場域", fam="店內", pose="站", hand="操作器具",
      gaze="看手上的東西", view="near", topo="窗光側面", time="day",
      ppl=dict(level="1-2人", dist="中", act="在吧檯另一側等自己那杯",
               wear="中目黑上班日會穿的便服，大衣或針織", facing="側對鏡頭"),
      pl="中目黑那間自家烘焙咖啡店的吧檯後面，營業時間，蒸氣正在上來",
      pl_en="behind the counter of the self-roasting coffee shop in Nakameguro during opening hours, steam coming up off the machine",
      ac="她低著頭在拉花，兩手一手壺一手杯，沒有抬頭",
      ac_en="Her head is down over the pour, one hand on the jug and one on the cup, and she does not look up.",
      ac_s="誰是她：現在是店裡拉花最穩的人",
      of="咖啡店的圍裙，帶子綁在前面",
      of_en="the shop's apron with the ties knotted at the front",
      of_s="小習慣：圍裙帶子綁在前面，不是後面",
      li="店面的窗光從側面進來，吧檯後方比較暗，蒸氣在光裡看得見",
      li_en="Window light from the shop front comes in from the side, it is darker behind the counter, and the steam is visible in the light.",
      li_s="後製原句：「暖木調、窗光為主，保留蒸氣與粉塵」",
      fa="完全專注，一句話也沒有",
      fa_en="Completely absorbed, not saying anything.",
      fa_s="語氣：極短、常常只有名詞",
      hair_en="tied back low and tucked under"),
 dict(id="M2", ev="下班繞去便利商店買那款布丁，回到公寓坐在地板上吃",
      pil="私下 / 一人公寓", wt="30%", flag=None, fam="客廳", pose="坐地", hand="雙手持物",
      gaze="垂眼", view="floor", topo="單一光源側前", time="night", ppl=None,
      pl="她那間很小的公寓，所有東西都在地板上，矮桌上放著那款布丁",
      pl_en="in her very small apartment where everything lives on the floor, that same convenience-store pudding on the low table",
      ac="她盤腿坐在矮桌前，兩手捧著布丁，湯匙還沒動",
      ac_en="She is sitting cross-legged at the low table holding the pudding in both hands, the spoon not yet used.",
      ac_s="小習慣：下班的路上會繞去便利商店買同一款布丁／公寓很小，所有東西都在地板上",
      of="寬鬆針織滑到肩下，裡面是棉質內衣",
      of_en="a loose knit slipping off one shoulder over cotton underthings",
      of_s="私下核心：寬鬆針織滑到肩下、棉質內衣",
      li="矮桌旁一盞小燈在她側前方偏低，公寓其餘部分暗",
      li_en="A small lamp beside the low table sits low and to one side of her, and the rest of the flat is dark.",
      li_s="氛圍原句：「木質暖調…安靜但有質地」",
      fa="面無表情地看著手上的布丁",
      fa_en="Looking at the pudding in her hands with no expression at all.",
      fa_s="幽默：面無表情地說很好笑的事，自己不笑",
      hair_en="down and slightly flattened from the day"),
 dict(id="M3", ev="白天休假走目黑川那一段，河邊有人在散步",
      pil="外出 / 中目黑", wt="15%", flag="房間以外", fam="街道", pose="走動", hand="空手",
      gaze="看側邊", view="full", topo="環境均勻", time="day", ppl=None,
      pl="中目黑目黑川旁邊的步道，白天，河的另一側是低矮的店",
      pl_en="on the walkway beside the Meguro river in Nakameguro in the daytime, low shopfronts along the far bank",
      ac="她沿著河走，兩手都空著，正要轉頭看水面",
      ac_en="She is walking along the river with both hands empty, turning her head towards the water.",
      ac_s="誰是她：中目黑",
      of="奶白色長版針織外套，裡面是米灰色的貼身上衣",
      of_en="a cream long knit cardigan over a fitted grey-beige top",
      of_s="色盤：奶白、米灰",
      li="白天的天光很均勻，水面反回來一點",
      li_en="The daylight is even and the water throws a little of it back.",
      li_s="後製原句：「不過度銳化」",
      fa="安靜，看著水",
      fa_en="Quiet, watching the water.",
      fa_s="語氣：像便條紙",
      hair_en="down and moving slightly"),
 dict(id="M4", ev="很晚了還是繞進便利商店，冷藏櫃前面站了一下",
      pil="外出 / 中目黑", wt="15%", flag="房間以外", fam="店內", pose="蹲", hand="單手持物",
      gaze="看手上的東西", view="knee", topo="環境均勻", time="night", ppl=None,
      pl="中目黑一間便利商店裡，深夜，她站在冷藏甜點櫃前",
      pl_en="inside a Nakameguro convenience store late at night, standing at the chilled dessert cabinet",
      ac="她蹲下來看下層剩下的，手上已經拿了一個",
      ac_en="She has crouched down to see what is left on the bottom shelf, one already in her hand.",
      ac_s="小習慣：下班的路上會繞去便利商店買同一款布丁",
      of="深咖啡色長大衣直接罩在家居服外面",
      of_en="a dark brown long coat thrown straight over what she wears at home",
      of_s="色盤：深咖啡",
      li="便利商店的白色頂燈很均勻，冷藏櫃自己也在發光",
      li_en="The store's white ceiling lighting is completely even and the chilled cabinet gives off its own light.",
      li_s="氛圍：這一格刻意不是暖木調，跟她的公寓形成對比",
      fa="認真在選，沒有在演",
      fa_en="Genuinely choosing, not performing.",
      fa_s="幽默：面無表情",
      hair_en="down and uncombed"),
 dict(id="M5", ev="很小的浴室，一天結束",
      pil="浴室 / 晨間", wt="20%", flag=None, fam="浴室", pose="倚牆", hand="單手扶物",
      gaze="看鏡頭", view="selfie", topo="單一光源正前", time="night", ppl=None,
      pl="她公寓那間很小的浴室，剛洗完，牆是舊的磁磚",
      pl_en="in the very small bathroom of her apartment straight after washing, old tiles on the wall",
      ac="她靠著牆，一手撐在洗手台邊",
      ac_en="She is leaning against the wall with one hand on the edge of the basin.",
      ac_s="私下核心：童顏配上這個身材的落差，而且她知道",
      of="米灰色浴巾",
      of_en="a grey-beige bath towel",
      of_s="色盤：米灰",
      li="鏡上那盞燈在她正前方，浴室很小所以光沒有地方可以跑",
      li_en="The light above the mirror is directly in front of her, and the room is small enough that the light has nowhere to go.",
      li_s="後製原句：「保留蒸氣與粉塵。不過度銳化」",
      fa="面無表情地看著鏡頭",
      fa_en="Looking at the lens with no expression.",
      fa_s="語氣：極短",
      hair_en="wet and pushed back off her face"),
])

SPECS["peggy-lee"] = dict(comp="3私0工2外", rhythm="2日3夜", slots=[
 dict(id="P1", ev="房間裡試那雙長靴，牆上還掛著那張車的海報",
      pil="私下 / 房間與車庫", wt="30%", flag=None, fam="臥室", pose="坐床沿", hand="單手扶物",
      gaze="看鏡頭", view="knee", topo="單一光源正前", time="night", ppl=None,
      pl="她房間的床邊，牆上掛著一張她那台車的海報，只有床頭一盞燈",
      pl_en="on the edge of the bed in her room, a poster of her own model of car pinned on the wall behind, one bedside lamp on",
      wall_ok="牆上那張車的海報是場景的一部分，守則不得禁止它",
      ac="她坐在床沿把長靴的拉鍊拉到底，一手扶著小腿",
      ac_en="She is sitting on the edge of the bed pulling the boot zip all the way up, one hand around her calf.",
      ac_s="私下核心：房間裡的貼身短版與長靴",
      of="黑色貼身短版上衣配短裙，長靴到膝上",
      of_en="a black fitted cropped top with a short skirt and boots over the knee",
      of_s="私下核心：貼身短版與長靴／色盤：黑",
      li="床頭那盞暖燈在她正前方，房間其餘部分全暗，對比很高",
      li_en="The warm bedside lamp is directly in front of her, the rest of the room completely dark, and the contrast is high.",
      li_s="後製原句：「高對比、金屬質感、夜間為主」",
      fa="很直接地看著鏡頭，沒有笑",
      fa_en="Looking very directly at the lens without smiling.",
      fa_s="語氣：爽快、直接",
      hair_en="down, the silver-grey strands catching the lamp"),
 dict(id="P2", ev="週末的車聚，她從高中就跟著跑",
      pil="夜衝 / 公路", wt="15%", flag="房間以外", fam="街道", pose="倚牆", hand="空手",
      gaze="看側邊", view="full", topo="背光", time="day",
      ppl=dict(level="數人", dist="遠", act="圍在別的車旁邊講話、蹲下來看輪圈",
               wear="車聚會穿的 T 恤、短褲、球鞋，有人戴著帽子", facing="背對鏡頭"),
      pl="吉隆坡郊區一場週末車聚的停車場，白天，一排改裝車停在那裡",
      pl_en="in the car park of a weekend car meet outside Kuala Lumpur in the daytime, a row of modified cars parked up",
      ac="她靠在自己那台車的側面，兩手都空著",
      ac_en="She is leaning against the side of her own car with both hands empty.",
      ac_s="誰是她：從高中就跟著哥哥們跑車聚",
      of="黑色短版背心配寬版工作褲",
      of_en="a black cropped vest with wide work trousers",
      of_s="色盤：黑、金屬灰",
      li="太陽在車陣那一側、在她背後，車漆把光反回鏡頭，她自己這一面暗一階",
      li_en="The sun is behind her over the line of cars, the paintwork throws it back towards the lens, and her own side sits a stop darker.",
      li_s="後製原句：「保留反光」——白天用車漆的反光，不是濕地面",
      fa="很自在，看著另一台車那邊",
      fa_en="Completely at ease, looking over towards one of the other cars.",
      fa_s="性格：她懂車，不是被放在車旁邊的擺設",
      hair_en="in a high ponytail"),
 dict(id="P3", ev="夜衝停在那間固定的加油站，人還坐在駕駛座上",
      pil="私下 / 房間與車庫", wt="30%", flag=None, fam="車內", pose="坐椅", hand="單手扶物",
      gaze="看側邊", view="near", topo="多光源", time="night", ppl=None,
      pl="她那台車的駕駛座上，停在夜衝固定會停的那間加油站",
      pl_en="in the driver's seat of her own car, pulled in at the petrol station she always stops at on a night run",
      ac="她一手還搭在排檔上，身體轉向副駕那一側",
      ac_en="One hand is still on the gear lever and she has turned towards the passenger side.",
      ac_s="小習慣：夜衝一定會在同一間加油站停／副駕永遠放著一條擦車布",
      of="黑色貼身長袖配皮質短褲",
      of_en="a black fitted long-sleeve top with leather shorts",
      of_s="色盤：黑",
      li="加油站的冷白頂燈從擋風玻璃外面進來，車內儀表板是琥珀色的",
      li_en="The station's cool white canopy lighting comes in through the windscreen while the dashboard inside glows amber.",
      li_s="氛圍原句：「車庫冷白日光燈、車燈紅黃…高對比、金屬感、夜間為主」",
      fa="沒有笑，看著副駕那一側",
      fa_en="Not smiling, looking across to the passenger side.",
      fa_s="語氣：直接",
      hair_en="down and slightly flattened"),
 dict(id="P4", ev="回家前在車庫停一下，引擎蓋開著，她沒打算現在弄",
      pil="私下 / 房間與車庫", wt="30%", flag=None, fam="車庫", pose="倚牆", hand="單手持物",
      gaze="看手上的東西", view="knee", topo="單一光源側前", time="night", ppl=None,
      pl="她家的車庫，夜裡，一盞工作燈打在打開的引擎蓋上",
      pl_en="in her own garage at night, a work lamp trained on the propped-open bonnet",
      ac="她靠在車尾，手上拿著那條擦車布，沒有要動手的意思",
      ac_en="She is leaning on the back of the car holding the cloth, with no intention of starting anything.",
      ac_s="小習慣：副駕永遠放著一條擦車布／指甲留短，因為要碰車",
      of="灰色寬版連身工作服，上半身脫下來綁在腰上，裡面是黑色短版背心",
      of_en="grey overalls with the top half peeled down and tied at her waist over a black cropped vest",
      of_s="色盤：金屬灰、黑",
      li="工作燈從她側前方打過來，車庫深處全暗，金屬反光很強",
      li_en="The work lamp reaches her from the side and in front, the back of the garage is completely dark, and the metal throws hard reflections.",
      li_s="後製原句：「高對比、金屬質感」",
      fa="低頭看著手上的布，有點懶得動",
      fa_en="Looking down at the cloth in her hand, not really inclined to move.",
      fa_s="幽默：很會虧自己",
      hair_en="tied up out of the way"),
 dict(id="P5", ev="白天出門前挑鞋，指甲還是留得很短",
      pil="穿搭", wt="20%", flag=None, fam="衣櫃 / 更衣", pose="蹲", hand="雙手持物",
      gaze="看手上的東西", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="她房間的鞋櫃前，白天，幾雙鞋已經被拿出來排在地上",
      pl_en="at the shoe rack in her room in the daytime, several pairs already pulled out and lined up on the floor",
      ac="她蹲在地上兩手拿著一隻鞋在看鞋底",
      ac_en="She is crouched on the floor turning one shoe over in both hands to look at the sole.",
      ac_s="小習慣：指甲留短，因為要碰車",
      of="琥珀黃色的短版針織配牛仔短褲",
      of_en="an amber-yellow cropped knit with denim shorts",
      of_s="色盤：琥珀黃",
      li="白天的窗光從側面進來，鞋櫃內側暗",
      li_en="Daylight comes in from the side and it stays dark inside the rack.",
      li_s="後製：白天的私下場景不套用夜間高對比",
      fa="很專心，沒有在看鏡頭",
      fa_en="Concentrating, not looking at the lens.",
      fa_s="語氣：講到車會突然變得很專業",
      hair_en="down over one shoulder"),
])

SPECS["ruoruo-tang"] = dict(comp="3私1工1外", rhythm="3日2夜", slots=[
 dict(id="R5", ev="夜裡回到墊子上，只做一個她自己最喜歡的體位",
      pil="私下 / 家裡的地墊", wt="30%", flag="標誌性配額", fam="客廳", pose="坐地", hand="空手",
      gaze="看鏡頭", view="low", topo="單一光源側前", time="night", ppl=None,
      pl="夜裡的地墊上，客廳只開了一盞落地燈",
      pl_en="on the mat at night, only one floor lamp on in the living room",
      ac="她坐在墊子上把身體往後折開，兩手都不扶，靠腰背撐住",
      ac_en="She is sitting on the mat with her body folded open backwards, neither hand supporting her, held there by her back and waist alone.",
      ac_s="標誌性配額：高難度體位／私下核心：這具身體能做到什麼",
      of="灰粉色貼身連身運動衣",
      of_en="a grey-pink fitted one-piece exercise suit",
      of_s="標誌性配額：連身運動衣",
      li="落地燈在她側前方偏低，客廳深處暗",
      li_en="The floor lamp sits low and to one side of her, and the far end of the room is dark.",
      li_s="後製原句：「強調線條的陰影但不刻意打亮」",
      fa="很穩，看著鏡頭",
      fa_en="Completely steady, looking at the lens.",
      fa_s="性格：她很清楚那些畫面有多好看",
      hair_en="in a low bun, a few strands loose"),
 dict(id="R1", ev="下午在家的地墊上拉伸，這是她自己的時間",
      pil="私下 / 家裡的地墊", wt="30%", flag=None, fam="客廳", pose="坐地", hand="單手扶物",
      gaze="垂眼", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="她家的地墊上，下午，一整面窗沿著一側牆",
      pl_en="on the exercise mat at home in the afternoon, a long window running down one wall",
      ac="她坐在墊子上把一條腿往前伸，手扶著腳踝把身體壓下去",
      ac_en="She is sitting on the mat with one leg extended, her hand at the ankle, folding herself down over it.",
      ac_s="私下核心：私下是家裡的地墊：拉伸、背肌與腰線",
      of="奶茶色貼身連身運動衣",
      of_en="a milk-tea coloured fitted one-piece exercise suit",
      of_s="標誌性配額：連身運動衣／色盤：奶茶色",
      li="大面窗的柔和側光落在她背上，房間低對比",
      li_en="Soft side light from the big window falls across her back and the room stays low in contrast.",
      li_s="後製原句：「柔和側光、低對比…強調線條的陰影但不刻意打亮」",
      fa="眼睛閉著一半，呼吸在數",
      fa_en="Her eyes half closed, counting the breath.",
      fa_s="語氣：溫和、清楚、有教學者的耐心",
      hair_en="in a low bun"), dict(id="R2", ev="那二十雙襪子每一雙都不一樣，她在挑今天要穿哪一雙",
      pil="穿搭", wt="15%", flag=None, fam="客廳", pose="跪坐", hand="雙手持物",
      gaze="看手上的東西", view="knee", topo="窗光側面", time="day", ppl=None,
      pl="地墊旁邊，一整排襪子攤在地板上，沒有兩雙一樣",
      pl_en="beside the mat with a whole row of socks laid out on the floor, no two pairs the same",
      ac="她跪坐著，兩手各拿一雙在比",
      ac_en="She is kneeling back on her heels with a pair in each hand, comparing them.",
      ac_s="小習慣：襪子有二十雙，每雙不一樣",
      of="灰粉色的貼身背心配同色系高腰褲",
      of_en="a grey-pink fitted vest with matching high-waisted leggings",
      of_s="色盤：灰粉",
      li="窗的柔和側光，地板的陰影很淺",
      li_en="Soft side light from the window, the shadows on the floor very shallow.",
      li_s="後製原句：「柔和側光、低對比」",
      fa="認真在比，有一點好笑",
      fa_en="Genuinely comparing them, and finding it slightly funny.",
      fa_s="幽默：溫吞的川式幽默",
      hair_en="in a low bun with strands loose at the neck"), dict(id="R3", ev="最後一堂課下了，她照慣例把器械再擦一遍",
      pil="器械皮拉提斯", wt="25%", flag="唯一的工作場域", fam="工作場域", pose="蹲", hand="單手持物",
      gaze="看手上的東西", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="她在成都那間只有四台器械的小教室，最後一堂課結束，只剩她一個人",
      pl_en="in her own small Chengdu studio with its four machines, the last class finished and only her left",
      ac="她蹲在器械旁邊，一手拿著布沿著底座的滑軌擦過去",
      ac_en="She is crouched down at the side of one machine, running a cloth along the rail at its base with one hand.",
      ac_s="小習慣：上課前一定把器械擦一遍",
      of="米白色貼身長袖配原木色高腰褲",
      of_en="an off-white fitted long-sleeve top with wood-toned high-waisted leggings",
      of_s="色盤：米白、原木",
      li="大面窗的柔和側光從她前方偏側進來，器械的陰影留在地上",
      li_en="Soft side light from the big window reaches her from the front and side, and the machines keep their shadows on the floor.",
      li_s="氛圍原句：「柔和側光加大面窗。安靜、乾淨、克制」",
      fa="很平靜，眼睛跟著手上的布",
      fa_en="Calm, her eyes following the cloth.",
      fa_s="語氣：說「再慢一點」的頻率極高",
      hair_en="in a low bun"), dict(id="R4", ev="傍晚走去巷子裡那間還開著的茶館",
      pil="外出 / 成都", wt="15%", flag="房間以外", fam="街道", pose="走動", hand="空手",
      gaze="看側邊", view="full", topo="環境均勻", time="night", ppl=None,
      pl="成都一條安靜的巷子，傍晚，巷底那間茶館還亮著",
      pl_en="in a quiet Chengdu lane in the early evening, the teahouse at the end of it still lit",
      ac="她沿著巷子往茶館走，兩手都空著",
      ac_en="She is walking down the lane towards the teahouse with both hands empty.",
      ac_s="誰是她：成都",
      of="淺灰色長版針織外套，裡面是米白貼身",
      of_en="a light grey long knit cardigan over something fitted and off-white",
      of_s="色盤：淺灰、米白",
      li="茶館的燈在巷底，巷子兩側暗下來",
      li_en="The teahouse light is at the far end and both sides of the lane fall away darker.",
      li_s="氛圍原句：「安靜、乾淨、克制」",
      fa="很鬆，看著巷底的光",
      fa_en="Relaxed, looking towards the light at the end.",
      fa_s="語氣：私下的貼文短而直接",
      hair_en="down and straight"),
])

SPECS["somi-oh"] = dict(comp="2私0工3外", rhythm="2日3夜", slots=[
 dict(id="S1", ev="白天回市場，她從小就在這些攤子之間長大",
      pil="吃播 / 外食", wt="25%", flag="房間以外", fam="市場", pose="站", hand="單手持物",
      gaze="看側邊", view="knee", topo="環境均勻", time="day",
      ppl=dict(level="數人", dist="中", act="在攤子前挑海鮮、跟攤商講價",
               wear="釜山市場白天的樣子，防水圍裙的攤商、拎著袋子的客人", facing="背對或側對鏡頭"),
      pl="釜山海鮮市場的走道，白天，水箱在兩側",
      pl_en="in the aisle of the Busan seafood market in the daytime, tanks along both sides",
      ac="她一手接過攤商遞來的東西，正要轉頭回話",
      ac_en="She is taking something handed to her with one hand, already turning to answer.",
      ac_s="誰是她：家裡在市場旁邊開店，她從小就在攤子之間長大",
      of="市場藍色的寬版襯衫，袖子捲起來，裡面是白色貼身",
      of_en="a market-blue oversized shirt with the sleeves rolled, something white and fitted underneath",
      of_s="色盤：市場藍",
      li="市場頂棚把白天的光濾成均勻的散射光，水箱反回來一點",
      li_en="The market canopy filters the daylight into an even wash and the tanks throw a little of it back.",
      li_s="氛圍原句：「市場的雜訊。高飽和、貼近」",
      fa="很大的表情，正在講話",
      fa_en="A big expression, mid-sentence.",
      fa_s="語氣：大聲、熱情、腔調很重",
      hair_en="down and pushed back behind both ears"),
 dict(id="S2", ev="深夜的路邊攤，吃之前先撩頭髮到耳後——那是她的招牌鏡頭",
      pil="吃播 / 外食", wt="25%", flag="房間以外", fam="街道", pose="坐椅", hand="整理頭髮",
      gaze="看鏡頭", view="near", topo="單一光源正前", time="night",
      ppl=dict(level="1-2人", dist="中", act="在隔壁桌吃東西、跟老闆點單",
               wear="深夜出來吃宵夜的人，外套、運動服", facing="背對鏡頭"),
      pl="釜山一個深夜的路邊攤，一張小桌，鍋子的蒸氣在上來",
      pl_en="at a Busan street stall late at night, one small table, steam coming up off the pot",
      ac="她坐下來先把頭髮撩到耳後，另一手已經拿著筷子",
      ac_en="She has sat down and is tucking her hair behind her ear first, chopsticks already in her other hand.",
      ac_s="小習慣：吃之前一定先撩頭髮到耳後，那是她的招牌鏡頭",
      of="暖橘色寬版連帽上衣",
      of_en="a warm orange oversized hoodie",
      of_s="色盤：暖橘",
      li="攤子那一盞燈在她正前方，攤子以外全暗，蒸氣在光裡",
      li_en="The stall's one lamp is directly in front of her, everything beyond the stall is dark, and the steam sits in the light.",
      li_s="後製原句：「食物特寫要有油光與熱氣」",
      fa="嘴角已經在笑，看著鏡頭",
      fa_en="Already smiling at the corners, looking at the lens.",
      fa_s="語氣：句子常常被嘴巴裡的東西打斷",
      hair_en="long, one side being tucked behind her ear"),
 dict(id="S3", ev="吃完宵夜回房間，什麼都不想做",
      pil="私下 / 深夜房間", wt="30%", flag=None, fam="臥室", pose="半躺", hand="空手",
      gaze="看鏡頭", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="她房間的床上，深夜，宵夜的袋子還丟在地上",
      pl_en="on the bed in her room late at night, the bag from supper still dropped on the floor",
      ac="她半躺在床上一隻手臂撐著頭，另一隻手垂在床邊",
      ac_en="She is half lying on the bed propped up on one arm, her other hand hanging over the edge.",
      ac_s="私下核心：吃完宵夜回房間，寬版 T 恤底下的鬆感、床上、深夜暖光",
      of="寬版白色 T 恤，領口滑到一邊肩膀",
      of_en="an oversized white T-shirt with the neckline slipped off one shoulder",
      of_s="私下核心：寬版 T 恤底下的鬆感",
      li="床頭一盞暖燈在她側前方，房間其餘部分暗",
      li_en="One warm bedside lamp reaches her from the side and in front, the rest of the room dark.",
      li_s="後製原句：「私下場景改為低光暖調」",
      fa="很懶，但眼睛看著鏡頭",
      fa_en="Thoroughly lazy, but her eyes on the lens.",
      fa_s="私下核心：私人平台上她把這件事講得更直接",
      hair_en="down and messy against the pillow"),
 dict(id="S4", ev="手機相簿滑到底全部都是食物，她自己都笑了",
      pil="私下 / 深夜房間", wt="30%", flag=None, fam="臥室", pose="坐地", hand="單手持物",
      gaze="看手上的東西", view="floor", topo="多光源", time="night", ppl=None,
      pl="她房間的地板上，背靠著床，深夜",
      pl_en="on the floor of her room with her back against the bed, late at night",
      ac="她一手拿著手機在滑，另一手撐在地板上",
      ac_en="She is scrolling with one hand, the other braced on the floor.",
      ac_s="小習慣：手機相簿全是食物",
      of="木色系的寬鬆家居長褲配貼身細肩帶上衣",
      of_en="loose wood-toned home trousers with a fitted strappy top",
      of_s="色盤：木色",
      li="手機螢幕的光加上床頭燈，兩個光源都在她前方偏低，背後全暗",
      li_en="The glow of the phone and the bedside lamp both sit low in front of her, and everything behind her is dark.",
      li_s="後製原句：「私下場景改為低光暖調」",
      fa="自己看著笑出來",
      fa_en="Laughing at it on her own.",
      fa_s="幽默：很會拿自己的食量開玩笑",
      screen_ok="手機螢幕上是她自己拍的食物照片，守則不得要求螢幕只能有純表面",
      hair_en="tied up in a loose knot"),
 dict(id="S5", ev="遠征到別的城市找吃的，市場白天正熱鬧",
      pil="旅遊 / 美食遠征", wt="15%", flag="房間以外", fam="市場", pose="走動", hand="雙手持物",
      gaze="看側邊", view="full", topo="背光", time="day",
      ppl=dict(level="數人", dist="遠", act="在攤子前排隊、端著吃的站著吃",
               wear="來吃早市的在地人，短袖、圍裙、提著袋子", facing="背對鏡頭"),
      pl="另一個城市的傳統市場外圍，白天，攤子沿街排開",
      pl_en="along the outer edge of a traditional market in another city in the daytime, stalls set out down the street",
      ac="她兩手各拿一樣邊走邊吃，正在看下一攤",
      ac_en="She is walking with something in each hand, eating as she goes and already looking at the next stall.",
      ac_s="誰是她：拍了幾支在市場吃東西的影片，數字好到她乾脆全職做",
      of="紅色短袖上衣配寬版長褲",
      of_en="a red short-sleeved top with wide trousers",
      of_s="色盤：紅",
      li="白天的天光很亮，攤子的遮陽布把光染成暖的",
      li_en="The daylight is bright and the stall awnings tint it warm as it comes through.",
      li_s="後製原句：「高飽和暖調」",
      fa="嘴裡有東西，表情很滿足",
      fa_en="Her mouth full, thoroughly pleased.",
      fa_s="語氣：大聲、熱情",
      hair_en="tied back with strands falling loose"),
])

SPECS["sydney-leong"] = dict(comp="3私1工1外", rhythm="3日2夜", slots=[
 dict(id="D1", ev="下午最熱的時候，三台風扇全開，她還在包裝",
      pil="烘焙工作", wt="25%", flag="唯一的工作場域", fam="工作場域", pose="坐椅", hand="雙手持物",
      gaze="看手上的東西", view="knee", topo="窗光側面", time="day", ppl=None,
      pl="喬治市老屋一樓的烘焙工作室，下午最熱的時候，三台風扇都開著",
      pl_en="in the ground-floor baking studio of the old George Town house in the hottest part of the afternoon, all three fans running",
      ac="她坐在長桌前兩手在綁一個盒子的緞帶，額頭上有汗",
      ac_en="She is sitting at the long table tying the ribbon on a box with both hands, and there is sweat at her hairline.",
      ac_s="誰是她：接單、烤、包裝",
      of="圍裙，上面的麵粉沒有擦掉，裡面是貼身背心",
      of_en="an apron with the flour on it left where it is, a fitted vest underneath",
      of_s="小習慣：圍裙上永遠有麵粉，她不擦／私下核心：圍裙底下只有貼身背心",
      li="老屋高窗的光從側面進來，風扇的影子在她身上動",
      li_en="Light from the old house's high window comes in from the side and the shadow of a fan moves across her.",
      li_s="後製原句：「保留熱氣與風扇的動態陰影」",
      fa="專心，熱到有點恍神",
      fa_en="Concentrating, slightly dazed by the heat.",
      fa_s="語氣：親切、句子軟",
      hair_en="tied up off her neck with strands stuck down"),
 dict(id="D2", ev="收工上樓，圍裙還沒脫，麵粉還沾在鎖骨上",
      pil="私下 / 老屋樓上", wt="30%", flag="標誌性配額", fam="客廳", pose="坐椅", hand="空手",
      gaze="看鏡頭", view="near", topo="窗光側面", time="day", ppl=None,
      pl="老屋樓上，收工後的午後，百葉窗的影子橫在牆上",
      pl_en="upstairs in the old house in the afternoon after finishing work, louvre shadows striped across the wall",
      ac="她往後靠在藤椅上，兩手都垂著，還沒力氣脫圍裙",
      ac_en="She has dropped back into the rattan chair with both hands hanging, without the energy yet to take the apron off.",
      ac_s="標誌性配額：圍裙 + 貼身背心／私下核心：麵粉沾在鎖骨與手臂上",
      of="圍裙還掛在脖子上，底下只有奶油黃的貼身背心",
      of_en="the apron still round her neck with only a butter-yellow fitted vest under it",
      of_s="標誌性配額：圍裙 + 貼身背心／色盤：奶油黃",
      li="南洋午後的斜光從百葉窗進來，在她身上留下條紋",
      li_en="The slanting tropical afternoon light comes through the louvres and leaves stripes across her.",
      li_s="私下核心原句：南洋午後的斜光／氛圍原句：「南洋自然光加風扇陰影」",
      fa="累到很鬆，看著鏡頭",
      fa_en="Tired enough to be completely loose, looking at the lens.",
      fa_s="幽默：憨憨的自嘲",
      hair_en="half fallen out of its tie"),
 dict(id="D3", ev="每天四點開烤箱，風雨無阻——所以三點半就得起來",
      pil="私下 / 老屋樓上", wt="30%", flag=None, fam="廚房", pose="站", hand="單手持物",
      gaze="垂眼", view="near", topo="單一光源正前", time="night", ppl=None,
      pl="老屋樓上的小廚房，凌晨三點半，只開了流理台上方那一盞",
      pl_en="in the small kitchen upstairs in the old house at half past three in the morning, only the light over the worktop switched on",
      ac="她一手端著杯子站在流理台前，還沒完全醒",
      ac_en="She is standing at the worktop with a cup in one hand, not fully awake yet.",
      ac_s="小習慣：每天四點開烤箱，風雨無阻",
      of="粉色的寬鬆睡衣上衣配短褲",
      of_en="a loose pink pyjama top with shorts",
      of_s="色盤：粉",
      li="流理台上方那一盞燈在她正前方，廚房其餘部分暗",
      li_en="The light over the worktop is directly in front of her and the rest of the kitchen is dark.",
      li_s="氛圍原句：「暖、潮、有生活感」",
      fa="眼睛還沒完全睜開，看著杯子",
      fa_en="Her eyes not fully open, looking down at the cup.",
      fa_s="語氣：句子軟",
      hair_en="down and flat from sleep"),
 dict(id="D4", ev="白天走出去買料，喬治市老街上都是人",
      pil="外出 / 檳城", wt="15%", flag="房間以外", fam="老街", pose="走動", hand="單手持物",
      gaze="看側邊", view="full", topo="環境均勻", time="day",
      ppl=dict(level="數人", dist="中", act="在店屋前走動、拍壁畫、停下來買東西",
               wear="喬治市白天的觀光客與在地人，短袖、草帽、背相機", facing="背對或側對鏡頭"),
      pl="喬治市一條白天的老街，五腳基與店屋的騎樓連成一排",
      pl_en="on an old George Town street in the daytime, the five-foot-ways of the shophouses running in a line",
      ac="她提著一袋材料走在騎樓下，正要轉進其中一間",
      ac_en="She is walking under the arcade with a bag of ingredients, about to turn into one of the shops.",
      ac_s="誰是她：只接預約單，一週做四天",
      of="老磁磚綠色的短袖上衣配藤編米色長裙",
      of_en="an old-tile-green short-sleeved top with a long rattan-beige skirt",
      of_s="色盤：老磁磚綠、藤編米",
      li="騎樓外面很亮、裡面比較暗，她走在兩者的交界",
      li_en="It is bright outside the arcade and darker inside it, and she is walking along the line between the two.",
      li_s="後製原句：「暖調自然光」",
      fa="很自然，看著要轉進去的那間",
      fa_en="Perfectly natural, looking at the shop she is about to turn into.",
      fa_s="語氣：有檳城腔",
      hair_en="down and slightly frizzy in the humidity"),
 dict(id="D5", ev="今天烤壞的那盤，她自己吃掉",
      pil="私下 / 老屋樓上", wt="30%", flag=None, fam="客廳", pose="跪坐", hand="雙手持物",
      gaze="看手上的東西", view="floor", topo="單一光源側前", time="night", ppl=None,
      pl="老屋樓上的矮桌前，夜裡，今天失敗的那一盤放在桌上",
      pl_en="at the low table upstairs in the old house at night, today's failed bake sitting on it",
      ac="她跪坐在矮桌前，兩手掰開其中一個",
      ac_en="She is kneeling back on her heels at the low table, breaking one of them open with both hands.",
      ac_s="小習慣：失敗的成品自己吃掉",
      of="奶油黃的寬鬆家居長洋裝",
      of_en="a loose butter-yellow house dress",
      of_s="色盤：奶油黃",
      li="矮桌旁一盞小燈在她側前方，房間其餘部分暗，空氣裡還有一點熱氣",
      li_en="A small lamp beside the low table reaches her from one side and in front, the rest of the room dark, a little heat still in the air.",
      li_s="後製原句：「保留熱氣」",
      fa="有點好笑地看著手上那個",
      fa_en="Looking at the one in her hands and finding it faintly funny.",
      fa_s="幽默：常拿烤壞的東西開玩笑",
      hair_en="down and loose"),
])

SPECS["tammy-chou"] = dict(comp="3私1工1外", rhythm="2日3夜", slots=[
 dict(id="T1", ev="清晨去五分埔批貨，那個時間店家正在拉開鐵門",
      pil="晨間 / 選貨", wt="10%", flag="房間以外", fam="街道", pose="走動", hand="雙手持物",
      gaze="看側邊", view="full", topo="多光源", time="day",
      ppl=dict(level="數人", dist="中", act="拉開鐵門、推著裝滿衣服的推車、在店門口點貨",
               wear="五分埔批貨的人，T 恤短褲、腰包、拖鞋", facing="背對或側對鏡頭"),
      pl="五分埔一條清晨的巷子，店家正在拉開鐵門，推車堆著衣服",
      pl_en="in a Wufenpu lane at dawn, shutters going up and trolleys stacked with clothes",
      ac="她兩手各提著一大袋貨往前走，正在看右邊那間",
      ac_en="She is walking with a big bag of stock in each hand, eyeing the shop on her right.",
      ac_s="小習慣：清晨去批貨",
      of="黑色貼身短版上衣配牛仔藍的寬褲",
      of_en="a black fitted cropped top with wide denim-blue trousers",
      of_s="色盤：黑、牛仔藍",
      li="清晨的天光還沒完全亮，巷子裡的日光燈還開著",
      li_en="The dawn light has not fully come up yet and the fluorescent tubes in the lane are still on.",
      li_s="氛圍原句：「飽和、明亮、有點吵」",
      fa="很有精神，正在挑",
      fa_en="Wide awake and already picking.",
      fa_s="語氣：快、大聲、很有節奏感",
      hair_en="in a high messy bun"),
 dict(id="T2", ev="同一件衣服她會拍三個角度，自己決定哪張上架",
      pil="換裝 / 試穿", wt="25%", flag=None, fam="臥室", pose="站", hand="整理衣物",
      gaze="看鏡頭", view="knee", topo="單一光源正前", time="day", ppl=None,
      pl="樓上她住的地方，白天，地板上散著今天還沒收的衣服",
      pl_en="in the room upstairs where she lives in the daytime, clothes she has not picked up still on the floor",
      ac="她一手把下襬扯平，另一手把領口往下拉一點，這是第三個角度",
      ac_en="One hand is pulling the hem flat and the other is easing the neckline down a little; this is the third angle she has tried.",
      ac_s="小習慣：一件衣服會用三種角度拍，自己決定哪張上架",
      of="米色的貼身針織洋裝",
      of_en="a beige fitted knit dress",
      of_s="色盤：米色",
      li="房間的補光燈很亮很平，地板上的衣服照樣入鏡",
      li_en="The fill light in the room is bright and flat, and the clothes on the floor stay in shot exactly as they are.",
      li_s="後製原句：「明亮飽和，不刻意精緻。允許雜物入鏡，那是真實感的來源」",
      fa="很直接地看著鏡頭，在評估自己",
      fa_en="Looking straight at the lens, assessing herself.",
      fa_s="私下核心：她比任何人都清楚自己哪個角度好看",
      hair_en="down and straightened"),
 dict(id="T3", ev="剛下播，妝還在臉上，化妝品攤了一檯面",
      pil="浴室 / 卸妝", wt="15%", flag=None, fam="浴室", pose="站", hand="單手扶物",
      gaze="看鏡頭", view="selfie", topo="環境均勻", time="night", ppl=None,
      pl="樓上的浴室，剛下播，檯面上化妝品攤開沒收",
      pl_en="in the bathroom upstairs straight off a live stream, makeup spread across the counter and not put away",
      ac="她一手撐著檯面，另一隻手上的卸妝棉才擦了半邊臉",
      ac_en="One hand is on the counter and the cotton pad in her other hand has only taken half her face off.",
      ac_s="支柱名稱：浴室 / 卸妝",
      of="螢光粉色的細肩帶家居上衣",
      of_en="a fluorescent-pink strappy home top",
      of_s="色盤：螢光粉",
      li="鏡上的燈條很亮，浴室其餘部分也是亮的——她不走暗色調",
      li_en="The strip lights at the mirror are bright and the rest of the bathroom is bright too; she does not do dark.",
      li_s="後製原句：「明亮飽和，不刻意精緻」",
      fa="半張臉有妝半張沒有，看著鏡頭笑",
      fa_en="Half her face still made up and half not, laughing at the lens.",
      fa_s="幽默：直播梗很多",
      hair_en="still set from the stream on one side, falling on the other"),
 dict(id="T4", ev="八點準時開播，倉庫的衣架陣就在她後面",
      pil="直播間幕後", wt="20%", flag="唯一的工作場域", fam="工作場域", pose="坐椅", hand="雙手持物",
      gaze="看側邊", view="knee", topo="環境均勻", time="night", ppl=None,
      pl="樓下的直播間，補光燈架著，後面是倉庫的衣架陣",
      pl_en="in the downstairs streaming room with the fill lights rigged and rails of stock behind her",
      ac="她坐在高腳椅上兩手把一件衣服撐開給鏡頭看",
      ac_en="She is on the high stool holding one piece open towards the camera with both hands.",
      ac_s="小習慣：說「這件我自己也留了一件」的頻率很高",
      of="高亮白的貼身上衣配黑色短裙",
      of_en="a bright white fitted top with a black short skirt",
      of_s="色盤：高亮白、黑",
      li="直播補光燈在她正前方，很亮很平，倉庫深處的衣架有一點暗",
      li_en="The streaming fill light is directly in front of her, bright and flat, and it is slightly darker back among the rails.",
      li_s="氛圍原句：「直播間的高亮補光加倉庫的雜亂真實感」",
      fa="很有精神在講話，看著旁邊的螢幕",
      fa_en="Talking with a lot of energy, her eyes on the monitor at the side.",
      fa_s="語氣：快、大聲、句尾常常上揚",
      hair_en="down and straightened, one side pushed back"),
 dict(id="T5", ev="播完上樓，紙箱還沒拆完就先坐下來了",
      pil="私下 / 貼身試穿", wt="30%", flag=None, fam="臥室", pose="坐床沿", hand="空手",
      gaze="看鏡頭", view="near", topo="環境均勻", time="night", ppl=None,
      pl="樓上房間的床邊，紙箱還沒拆完，床上堆著剛到的貨",
      pl_en="on the edge of the bed upstairs with boxes still half unpacked and new stock piled on the bed",
      ac="她往後靠在手上坐著，腳還在地上，什麼都不想拆了",
      ac_en="She is sitting propped back on her hands with her feet still on the floor, done with unpacking anything.",
      ac_s="誰是她：樓下是倉庫兼直播間、樓上住人",
      of="牛仔藍色的寬版襯衫，只扣中間兩顆，裡面是黑色貼身",
      of_en="a denim-blue oversized shirt buttoned only at the middle over something black and fitted",
      of_s="色盤：牛仔藍、黑",
      li="房間的燈很亮很平，紙箱與雜物都在畫面裡",
      li_en="The room light is bright and flat, and the boxes and clutter are all in the frame.",
      li_s="後製原句：「允許雜物入鏡，那是真實感的來源」",
      fa="累但還在笑，看著鏡頭",
      fa_en="Tired but still laughing, looking at the lens.",
      fa_s="幽默：很會自嘲批貨的糗事",
      hair_en="pulled up into a clip, bits falling out"),
])

SPECS["wanyin-jiang"] = dict(comp="3私1工1外", rhythm="3日2夜", slots=[
 dict(id="Q1", ev="下雨天她一定去園林走一趟，那天遊客不多但還是有",
      pil="外出 / 園林", wt="15%", flag="房間以外", fam="園林 / 戶外自然", pose="站", hand="單手持物",
      gaze="看側邊", view="full", topo="背光", time="day", ppl=None,
      pl="蘇州一座園林的迴廊下，下雨天，水面有雨點，這個時間沒有別人",
      pl_en="under the covered walkway of a Suzhou garden on a rainy day, the water dimpled with rain and nobody else out at this hour",
      ac="她一手提著傘收在身側，人停在柱子旁邊看水",
      ac_en="She has the umbrella closed at her side and has stopped by one of the columns to look at the water.",
      ac_s="小習慣：下雨天一定去園林走一趟",
      of="月白色旗袍，外面罩一件薄外套",
      of_en="a moon-white qipao with a thin jacket over it",
      of_s="色盤：月白／標誌性配額以外的日常旗袍",
      li="雨天的光是均勻的灰白，迴廊裡比外面暗",
      li_en="The rainy-day light is an even grey-white and it is darker under the walkway than outside it.",
      li_s="氛圍原句：「光線像宣紙。園林的水、雨、木格窗」",
      fa="很安靜，看著水面",
      fa_en="Very quiet, watching the surface of the water.",
      fa_s="語氣：文雅、簡短",
      hair_en="in a low coiled bun pinned by herself"),
 dict(id="Q2", ev="夜裡的老宅臥房，一顆一顆解盤扣",
      pil="換裝 / 盤扣", wt="20%", flag="標誌性配額", fam="臥室", pose="站", hand="整理衣物",
      gaze="垂眼", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="蘇州老宅的臥房，木格窗，一張老木床，只有一盞燈",
      pl_en="in the bedroom of the old Suzhou house, a lattice window, an old wooden bed, one lamp",
      ac="她站在床邊一顆一顆解開領口的盤扣，動作很慢",
      ac_en="She is standing by the bed undoing the knotted buttons at the collar one at a time, very slowly.",
      ac_s="標誌性配額：旗袍 / 漢服半褪／私下核心：盤扣一顆一顆解開",
      of="胭脂紅的絲質旗袍，領口已經解開三顆",
      of_en="a rouge-red silk qipao with the top three knotted buttons already undone",
      of_s="色盤：胭脂紅",
      li="那一盞燈在她側前方，光像宣紙一樣柔，木格窗與房間深處落暗",
      li_en="The single lamp is to one side and in front of her, the light as soft as paper, the lattice window and the far side of the room falling dark.",
      li_s="氛圍原句：「低飽和、高質感，光線像宣紙」",
      fa="眼睛往下看著自己的手",
      fa_en="Her eyes down on her own hands.",
      fa_s="幽默：常常用一句很雅的話講很不雅的事",
      hair_en="coiled up, with one pin being loosened"),
 dict(id="Q3", ev="早上自己盤髮，這件事她從不假手他人",
      pil="浴室 / 晨間梳妝", wt="15%", flag=None, fam="臥室", pose="坐椅", hand="整理頭髮",
      gaze="看側邊", view="near", topo="窗光側面", time="day", ppl=None,
      pl="老宅臥房的梳妝檯前，早上，量身的軟尺掛在椅背上",
      pl_en="at the dressing table in the old house's bedroom in the morning, her tailoring tape hanging over the back of the chair",
      ac="她兩手在腦後盤髮，髮簪咬在嘴裡",
      ac_en="Both hands are behind her head coiling her hair, the pin held in her teeth.",
      ac_s="小習慣：盤髮永遠自己來，不假手他人／量身的軟尺掛在脖子上一整天",
      of="黛青色的絲質內搭，外面還沒套旗袍",
      of_en="a dark blue-green silk under-layer, the qipao not yet put on over it",
      of_s="色盤：黛青",
      li="木格窗的晨光從側面進來，梳妝檯那一側亮、房間深處暗",
      li_en="Morning light through the lattice window comes in from the side, bright at the dressing table and dark further into the room.",
      li_s="後製原句：「低飽和、柔光、留白構圖」",
      fa="很專注，看著側邊",
      fa_en="Completely absorbed, looking off to the side.",
      fa_s="語氣：貼文常常只有四個字",
      hair_en="halfway into a coil, one long section still loose"),
 dict(id="Q4", ev="客人走了，長桌上還攤著今天挑的料",
      pil="旗袍店工作 / 量身", wt="20%", flag="唯一的工作場域", fam="工作場域", pose="坐椅", hand="雙手持物",
      gaze="看手上的東西", view="knee", topo="背光", time="day", ppl=None,
      pl="老宅一樓的旗袍店，打烊後，料子攤在長桌上，木格窗外是天井",
      pl_en="in the qipao workshop on the ground floor of the old house after closing, bolts of cloth spread across the long table, the courtyard visible through the lattice window",
      ac="她坐在長桌旁兩手展開一段布，背對木格窗把布舉起來讓光透過去看織紋",
      ac_en="She is sitting at the long table with a length of cloth open in both hands, her back to the lattice window, holding it up so the light comes through the weave.",
      ac_s="誰是她：量身、選料、做衣服",
      of="竹青色的旗袍，軟尺掛在脖子上",
      of_en="a bamboo-green qipao with the tailoring tape round her neck",
      of_s="色盤：竹青／小習慣：軟尺掛在脖子上一整天",
      li="天井的光從她背後的木格窗進來，布被照透，她自己這一面比較暗",
      li_en="Light from the courtyard comes through the lattice window behind her, shining through the cloth, leaving her own side of it darker.",
      li_s="氛圍原句：「園林的水、雨、木格窗」",
      fa="很專業地在看布",
      fa_en="Reading the cloth quite professionally.",
      fa_s="性格：這件事她做得非常自覺",
      hair_en="coiled up neatly"),
 dict(id="Q5", ev="夜裡在老木床上，一天結束",
      pil="私下 / 老宅暗光", wt="30%", flag=None, fam="臥室", pose="半躺", hand="空手",
      gaze="看鏡頭", view="low", topo="單一光源側前", time="night", ppl=None,
      pl="老宅的老木床上，夜裡，床帳的一邊垂下來",
      pl_en="on the old wooden bed in the old house at night, one side of the bed curtain hanging down",
      ac="她側躺在床上，一隻手臂枕在頭下",
      ac_en="She is lying on her side with one arm folded under her head.",
      ac_s="私下核心：老宅裡的暗光與木床",
      of="月白色的絲質內衣兩件式",
      of_en="a moon-white two-piece silk set",
      of_s="色盤：月白",
      li="床邊那一盞燈在她側前方很低，床帳把光擋掉一半",
      li_en="The lamp by the bed sits low and to one side and the bed curtain takes out half of what reaches her.",
      li_s="後製原句：「低飽和、柔光、留白構圖」",
      fa="很平靜地看著鏡頭",
      fa_en="Looking at the lens completely calmly.",
      fa_s="私下核心：完全不靠裸露",
      hair_en="taken down, long and loose across the pillow"),
])

SPECS["wendy-yeo"] = dict(comp="3私1工1外", rhythm="2日3夜", slots=[
 dict(id="W1", ev="打烊後她一定自己擦完最後一輪杯子，冰球也是自己切的",
      pil="吧檯工作", wt="25%", flag="唯一的工作場域", fam="工作場域", pose="站", hand="雙手持物",
      gaze="看手上的東西", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="丹戎巴葛那間十六個位子的酒吧，打烊後，只剩吧檯上那一盞燈",
      pl_en="in the sixteen-seat bar in Tanjong Pagar after closing, only the one lamp over the counter still on",
      ac="她兩手拿著一只杯子在擦，動作沒有停",
      ac_en="She has a glass in both hands and is polishing it without stopping.",
      ac_s="小習慣：打烊後一定自己擦完最後一輪杯子／冰球是自己切的",
      of="白襯衫袖子捲到手肘上方三指，最上面解到第三顆",
      of_en="a white shirt with the sleeves rolled three fingers above the elbow and the top three buttons open",
      of_s="小習慣：袖子永遠捲到手肘上方三指／標誌性配額：吧檯 + 解開的襯衫",
      li="吧檯上那一盞燈在她側前方偏低，酒櫃深處全暗，玻璃把光反回來",
      li_en="The counter lamp sits low and to one side of her, the back of the bar is completely dark, and the glass throws the light back.",
      li_s="氛圍原句：「單一暖光源加大量陰影，酒液透光」",
      fa="臉有一半在暗裡，沒有看鏡頭",
      fa_en="Half her face is in shadow and she is not looking at the lens.",
      fa_s="後製原句：「臉部可以在半明半暗之間」",
      hair_en="pulled back into a low knot"),
 dict(id="W2", ev="白天窗簾拉到底，這是她的睡覺時間",
      pil="私下 / 打烊後與白天", wt="30%", flag=None, fam="臥室", pose="半躺", hand="空手",
      gaze="閉眼", view="floor", topo="單一光源側前", time="day", ppl=None,
      pl="她公寓的臥室，白天，窗簾拉到底，只有縫隙漏進來的一線光",
      pl_en="in her apartment bedroom in the middle of the day, the curtains pulled all the way across, a single line of light getting through the gap",
      ac="她趴在床上一隻手臂攤開，另一隻壓在身體底下",
      ac_en="She is face down on the bed with one arm flung out and the other trapped under her.",
      ac_s="小習慣：白天窗簾拉到底",
      of="黑色的絲質睡衣上衣，下襬掀起來一點",
      of_en="a black silk sleep shirt riding up a little at the hem",
      of_s="色盤：黑",
      li="窗簾縫的那一道光落在她的背與肩上，房間其餘部分暗",
      li_en="The line of light from the curtain gap lands across her back and shoulder and the rest of the room stays dark.",
      li_s="後製原句：「低光高對比，保留陰影」",
      fa="眼睛閉著，睡到一半",
      fa_en="Her eyes closed, halfway through sleep.",
      fa_s="語氣：低、慢",
      hair_en="loose and spread across the pillow"),
 dict(id="W3", ev="起來以後在客廳自己調一杯，不為了誰",
      pil="私下 / 打烊後與白天", wt="30%", flag=None, fam="客廳", pose="坐椅", hand="單手持物",
      gaze="看側邊", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="她公寓的客廳，夜裡，一盞黃銅落地燈，矮桌上一杯自己調的",
      pl_en="in her own living room at night, one brass floor lamp, a drink she has made herself on the low table",
      ac="她窩在沙發角落，一手端著杯子舉在胸前",
      ac_en="She is curled into the corner of the sofa with the glass held up in front of her.",
      ac_s="私下核心：她的性感是「主導權」",
      of="深綠色的絲質長袍鬆鬆綁著",
      of_en="a dark green silk robe loosely tied",
      of_s="色盤：深綠",
      li="落地燈在她側前方，沙發另一半與房間深處全暗，杯裡的酒透光",
      li_en="The floor lamp is to one side and in front of her, the other half of the sofa and the far side of the room completely dark, the liquid in the glass lit through.",
      li_s="氛圍原句：「酒液透光。低、慢、有質感」",
      fa="挑了一下眉，看著旁邊",
      fa_en="One eyebrow going up, looking off to the side.",
      fa_s="幽默：一句話配一個挑眉",
      hair_en="down and slightly slept-on"),
 dict(id="W4", ev="白天出門前把襯衫的袖子捲好，三指，每次都一樣",
      pil="穿搭", wt="15%", flag=None, fam="衣櫃 / 更衣", pose="站", hand="整理衣物",
      gaze="看手上的東西", view="near", topo="窗光側面", time="day", ppl=None,
      pl="她公寓的衣櫃前，白天，一整排深色襯衫",
      pl_en="in front of the wardrobe in her apartment in the daytime, a whole row of dark shirts",
      ac="她低頭把左邊的袖子往上捲，抓到手肘上方三指的位置",
      ac_en="Head down, she is rolling the left sleeve up to exactly three fingers above the elbow.",
      ac_s="小習慣：袖子永遠捲到手肘上方三指",
      of="暗木色的襯衫，下襬紮進黑色長褲",
      of_en="a dark wood-toned shirt tucked into black trousers",
      of_s="色盤：暗木、黑",
      li="白天的窗光從側面進來，衣櫃內側暗",
      li_en="Daylight comes in from the side and it stays dark inside the wardrobe.",
      li_s="後製原句：「手部…的特寫要清晰」——這一格重點在手",
      fa="低著頭，專心在袖子上",
      fa_en="Head down, attention entirely on the sleeve.",
      fa_s="語氣：句子短",
      hair_en="pulled back off her face"),
 dict(id="W5", ev="週日不上班，去東海岸那間開到很晚的老咖啡攤",
      pil="外出 / 休假", wt="15%", flag="房間以外", fam="店內", pose="坐椅", hand="單手持物",
      gaze="看鏡頭", view="knee", topo="環境均勻", time="night", ppl=None,
      pl="東海岸一間開到很晚的老咖啡攤，週日入夜，塑膠椅與鐵桌",
      pl_en="at an old East Coast coffee stall that stays open late on a Sunday night, plastic chairs and a metal table",
      ac="她一手端著杯子擱在桌上，身體往椅背靠",
      ac_en="One hand rests the cup on the table and she has leaned back into the chair.",
      ac_s="誰是她：她的工作是掌控一個空間的節奏——這一格她不控制任何東西",
      of="琥珀色的寬版襯衫，袖子一樣捲著",
      of_en="an amber oversized shirt with the sleeves rolled the same way",
      of_s="色盤：琥珀",
      li="咖啡攤的日光燈很平很白，攤子以外的路面暗",
      li_en="The stall's fluorescent lighting is flat and white, and the road beyond it is dark.",
      li_s="氛圍：這一格刻意不是她的單一暖光，休假時她不布光",
      fa="很鬆，看著鏡頭，沒有挑眉",
      fa_en="Completely relaxed, looking at the lens, no raised eyebrow this time.",
      fa_s="語氣：低、慢、句子短",
      hair_en="down, longer than it looks when tied"),
])

SPECS["yerin-han"] = dict(comp="2私1工2外", rhythm="3日2夜", slots=[
 dict(id="Y1", ev="白天在練習場帶課，旁邊的打位也有人在打",
      pil="練習場 / 教課", wt="20%", flag="唯一的工作場域", fam="工作場域", pose="站", hand="雙手持物",
      gaze="看手上的東西", view="knee", topo="環境均勻", time="day",
      ppl=dict(level="1-2人", dist="遠", act="在自己的打位揮桿、彎腰放球",
               wear="室內練習場的球衣、手套、球帽", facing="背對鏡頭"),
      pl="首爾市區室內練習場她那個固定打位，白天上課中，隔壁打位也有人",
      pl_en="at her regular bay in an indoor driving range in central Seoul during a daytime lesson, someone in the next bay too",
      ac="她兩手握著桿示範握法，眼睛跟著自己的手指看",
      ac_en="Both hands are on the club showing the grip, her eyes following her own fingers.",
      ac_s="小習慣：記得每個學生的握桿毛病／室內練習場的固定打位不讓人",
      of="白色的短袖球衫配草地綠的短裙",
      of_en="a white short-sleeved golf top with a grass-green skirt",
      of_s="色盤：白、草地綠／標誌性配額：球場短裙",
      li="練習場上方的冷白燈很均勻，每個打位都亮",
      li_en="The cool white lighting above the range is completely even and every bay is lit.",
      li_s="氛圍原句：「室內練習場的冷白光為主…明亮但膚色維持白皙」",
      fa="教學中，眼睛在自己的手上",
      fa_en="Mid-lesson, her eyes on her own hands.",
      fa_s="語氣：開朗、有活力",
      hair_en="in a ponytail pulled through the back of a cap"),
 dict(id="Y2", ev="教完課回公寓，球具袋就靠在牆邊沒收",
      pil="私下 / 首爾的家", wt="30%", flag=None, fam="客廳", pose="半躺", hand="單手扶物",
      gaze="看鏡頭", view="floor", topo="單一光源側前", time="night", ppl=None,
      pl="她首爾公寓的客廳，夜裡，球具袋靠在牆邊，只開了一盞落地燈",
      pl_en="in the living room of her Seoul apartment at night, her golf bag propped against the wall, one floor lamp on",
      ac="她半躺在沙發上，一手撐在扶手上，一條腿掛在沙發外面",
      ac_en="She is half lying along the sofa with one hand on the arm of it and one leg hanging over the edge.",
      ac_s="私下核心：球具靠在牆邊的自拍",
      of="白色的貼身背心配過膝襪",
      of_en="a white fitted vest with over-the-knee socks",
      of_s="私下核心：貼身背心、過膝襪",
      li="落地燈在她側前方，客廳深處與球具袋落在暗處",
      li_en="The floor lamp is to one side and in front of her, and the far side of the room and the golf bag fall into shadow.",
      li_s="後製原句：「明亮清晰，但主動壓抑曬黑感」——夜間仍維持冷白膚色",
      fa="跟白天完全不同的溫度，看著鏡頭",
      fa_en="A completely different temperature from the daytime, looking at the lens.",
      fa_s="私下核心：這個落差比戶外的短裙更有效",
      hair_en="down out of the ponytail, with a bend where the tie was"),
 dict(id="Y3", ev="睡前那三罐防曬排在床頭櫃上，明天還是要補",
      pil="浴室 / 晨間", wt="15%", flag=None, fam="臥室", pose="坐床沿", hand="單手持物",
      gaze="看手上的東西", view="near", topo="單一光源正前", time="night", ppl=None,
      pl="她公寓的床邊，夜裡，床頭櫃上排著三罐防曬",
      pl_en="on the edge of the bed in her apartment at night, three bottles of sunscreen lined up on the nightstand",
      ac="她坐在床沿把其中一罐拿起來看背面的日期",
      ac_en="She is sitting on the edge of the bed with one of them picked up, checking the date on the back.",
      ac_s="小習慣：防曬每兩小時補一次，行李裡永遠有三罐",
      of="米色的絲質睡衣兩件式",
      of_en="a beige two-piece silk sleep set",
      of_s="色盤：米",
      li="床頭那盞燈在她正前方，房間其餘部分暗",
      li_en="The bedside lamp is directly in front of her and the rest of the room is dark.",
      li_s="後製原句：「皮膚維持冷白，強調防曬設定」",
      fa="很認真在看標示",
      fa_en="Reading the label quite seriously.",
      fa_s="幽默：愛開自己的玩笑",
      hair_en="down and unstyled"),
 dict(id="Y4", ev="下課後去市區那間運動用品店，白天門口一直有人進出",
      pil="高球穿搭", wt="20%", flag="房間以外", fam="車內", pose="坐椅", hand="單手扶物",
      gaze="看側邊", view="near", topo="背光", time="day", ppl=None,
      pl="她自己那台車的駕駛座，白天，正要開去球場，後座放著球具袋",
      pl_en="in the driver's seat of her own car in the daytime on the way out to the course, her golf bag on the back seat",
      ac="她一手搭在方向盤上，人轉向副駕那一側拿東西",
      ac_en="One hand rests on the wheel as she turns towards the passenger side to reach for something.",
      ac_s="誰是她：穿搭的流量比揮桿還好",
      of="金色系的針織背心配白色寬褲",
      of_en="a gold-toned knit vest with white wide-leg trousers",
      of_s="色盤：金、白",
      li="太陽在她身後的後擋風玻璃那一側，車內比車外暗一階",
      li_en="The sun is behind her through the rear screen, and the inside of the car sits a stop darker than everything outside it.",
      li_s="後製原句：「明亮清晰」",
      fa="很有精神，看著副駕那一側",
      fa_en="Full of energy, looking across to the passenger side.",
      fa_s="語氣：句尾常常上揚",
      hair_en="in a high ponytail"),
 dict(id="Y5", ev="週末真的上球場那天，開球前在果嶺邊等",
      pil="旅遊 / 球場遠征", wt="15%", flag="房間以外", fam="園林 / 戶外自然", pose="站", hand="單手持物",
      gaze="看側邊", view="full", topo="環境均勻", time="day", ppl=None,
      pl="週末的球場，開球前，果嶺那一側的草坡連到遠處的樹線",
      pl_en="out on the course at the weekend before the tee-off, the slope by the green running to a tree line in the distance",
      ac="她一手拄著球桿站著等，重心壓在一腳",
      ac_en="She is waiting with the club planted, her weight down on one leg.",
      ac_s="誰是她：週末才真的上球場",
      of="天空藍的短袖球衫配白色短裙，戴著球帽",
      of_en="a sky-blue short-sleeved golf top with a white skirt and a cap",
      of_s="色盤：天空藍、白",
      li="戶外的天光很開，草地把光反上來",
      li_en="The open daylight is wide and the grass bounces some of it back up.",
      li_s="氛圍原句：「戶外期才有草地綠。明亮但膚色維持白皙」",
      fa="很放鬆，看著球道那一側",
      fa_en="Relaxed, looking off down the fairway.",
      fa_s="語氣：開朗、有活力",
      hair_en="ponytail pulled through the cap, moving in the wind"),
])

SPECS["zhiyi-shen"] = dict(comp="4私0工1外", rhythm="2日3夜", slots=[
 dict(id="Z1", ev="十一點多進門，只脫外套，其他的等一下再說",
      pil="私下 / 還沒換下班的樣子", wt="30%", flag="標誌性配額", fam="玄關", pose="站", hand="單手持物",
      gaze="看鏡頭", view="knee", topo="單一光源正前", time="night", ppl=None,
      pl="她公寓的玄關，剛進門，高跟鞋已經在旁邊排成一列",
      pl_en="just inside the entryway of her apartment, her heels already lined up along the side",
      ac="她一手把外套拎在手上，另一手還沒放下包，人還站在玄關",
      ac_en="Her coat is over one hand and she has not put the bag down yet, still standing in the entryway.",
      ac_s="小習慣：回家只脫外套，其他的等一下再說／高跟鞋在玄關排成一列",
      of="襯衫、窄裙、黑絲都還穿著，外套已經脫在手上",
      of_en="still in the shirt, the pencil skirt and black stockings, the coat already off over her arm",
      of_s="標誌性配額：OL 制服的私下版（襯衫、絲襪）／私下核心：只脫掉外套",
      li="玄關那一盞暖燈打在她身上，客廳深處沒開燈",
      li_en="The one warm light in the entryway lands on her and nothing is on further into the flat.",
      li_s="後製原句：「私下場景改用單一暖光，讓落差成立」",
      fa="很累但很直接地看著鏡頭",
      fa_en="Exhausted but looking very directly at the lens.",
      fa_s="語氣：冷靜、簡潔、有點禦姊感",
      hair_en="still up from the office, coming loose at the sides"),
 dict(id="Z2", ev="夜深了坐在落地窗前，外面的塔還亮著",
      pil="私下 / 還沒換下班的樣子", wt="30%", flag=None, fam="客廳", pose="坐地", hand="空手",
      gaze="看側邊", view="floor", topo="背光", time="night", ppl=None,
      pl="她公寓的落地窗前，深夜，陸家嘴的塔還亮著",
      pl_en="against the frame of the floor-to-ceiling window in her apartment late at night, the Lujiazui towers still lit outside",
      ac="她坐在地板上背靠著窗框，兩腿曲著，兩手都空著",
      ac_en="She is sitting on the floor with her back against the window frame, knees drawn up and both hands empty.",
      ac_s="私下核心：落地窗前的夜景",
      of="黑色的絲質睡衣上衣，黑絲已經脫了",
      of_en="a black silk sleep shirt, the stockings finally off",
      of_s="色盤：黑",
      li="城市的燈在她身後，室內沒開燈，她的輪廓被窗光描出來",
      li_en="The city light is behind her with nothing on indoors, so the window draws her outline.",
      li_s="氛圍原句：「玻璃、金屬、夜景。冷灰藍加城市燈火，高級但有溫度」",
      fa="放空，看著窗外",
      fa_en="Emptied out, looking out of the window.",
      fa_s="語氣：不撒嬌，句子很短",
      hair_en="fully down for the first time that day"),
 dict(id="Z3", ev="週末白天整理那排高跟鞋，五雙裡她只常穿兩雙",
      pil="穿搭", wt="20%", flag=None, fam="衣櫃 / 更衣", pose="蹲", hand="雙手持物",
      gaze="看手上的東西", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="她公寓的衣帽間，白天，一排深色西裝外套與襯衫，地上五雙高跟鞋",
      pl_en="in the dressing room of her apartment in the daytime, a row of dark jackets and shirts, five pairs of heels on the floor",
      ac="她蹲在地上兩手拿著一隻鞋在看鞋跟",
      ac_en="She is crouched down turning one shoe over in both hands to look at the heel.",
      ac_s="小習慣：高跟鞋在玄關排成一列（週末才收回衣帽間）",
      of="冷灰藍色的家居長袖配同色短褲",
      of_en="a cool grey-blue long-sleeved home top with matching shorts",
      of_s="色盤：冷灰藍",
      li="白天的窗光從側面進來，衣物的深色把背景吃暗",
      li_en="Daylight comes in from the side and the dark clothes eat the background down.",
      li_s="後製原句：「私下場景改用單一暖光」——白天這一格改用窗光，不硬套暖燈",
      fa="很專心，沒有在看鏡頭",
      fa_en="Concentrating, not looking at the lens.",
      fa_s="語氣：冷靜、簡潔",
      hair_en="tied up in a low knot"),
 dict(id="Z4", ev="十一點下樓，大樓外面還有人在等車",
      pil="通勤 / 辦公", wt="20%", flag="房間以外", fam="街道", pose="站", hand="單手持物",
      gaze="看手上的東西", view="full", topo="多光源", time="night", ppl=None,
      pl="陸家嘴她那棟辦公大樓外面，十一點，玻璃帷幕在她上方還亮著",
      pl_en="outside her office tower in Lujiazui at eleven at night, the glass curtain wall still lit above her",
      ac="她一手拿著手機站在路邊等車，外套搭在另一隻手上",
      ac_en="She is at the kerb with her phone in one hand waiting for a car, her coat over her other arm.",
      ac_s="誰是她：加班到十一點",
      of="黑色西裝窄裙套裝配黑絲與高跟鞋",
      of_en="a black tailored skirt suit with black stockings and heels",
      of_s="標誌性配額以外的正規 OL 穿著",
      li="大樓的玻璃光加上街燈，兩個光源都在她側邊，馬路對面暗",
      li_en="Light off the building's glass and the street lights both reach her from the side, and the far side of the road is dark.",
      li_s="後製原句：「冷調高對比的辦公與街景」",
      fa="沒有表情，眼睛在手機上",
      fa_en="No expression at all, her eyes on the phone.",
      fa_s="幽默：黑色幽默，最常拿加班開玩笑",
      hair_en="up in a low knot, tidy after a long day"),
 dict(id="Z5", ev="出差住的飯店，白天有半天不用開會",
      pil="飯店 / 出差", wt="15%", flag=None, fam="臥室", pose="坐椅", hand="單手持物",
      gaze="看側邊", view="knee", topo="窗光側面", time="day", ppl=None,
      pl="出差飯店的房間，白天，窗簾拉開，桌上放著還沒收的資料",
      pl_en="in a hotel room on a work trip in the daytime, the curtains open and papers still out on the desk",
      ac="她側坐在書桌的椅子上，一手拿著杯子，人轉向窗那一邊",
      ac_en="She is sitting sideways on the desk chair with a cup in one hand, turned towards the window.",
      ac_s="誰是她：飯店 / 出差",
      of="玻璃白色的襯衫，下襬沒紮，配窄裙",
      of_en="a glass-white shirt left untucked over a pencil skirt",
      of_s="色盤：玻璃白",
      li="白天的窗光從側面進來，房間另一側暗",
      li_en="Daylight comes in from the side and the far side of the room stays darker.",
      li_s="後製原句：「冷調高對比」——出差仍屬工作側的冷調",
      fa="很鬆，看著窗外",
      fa_en="Relaxed, looking out of the window.",
      fa_s="語氣：句子很短",
      hair_en="down and slightly waved"),
])

SPECS["zoey-yeh"] = dict(comp="3私1工1外", rhythm="3日2夜", slots=[
 dict(id="O1", ev="下雨天不營業，她在門口貼紙條",
      pil="花店日常", wt="25%", flag="唯一的工作場域", fam="工作場域", pose="站", hand="雙手持物",
      gaze="看手上的東西", view="near", topo="背光", time="day", ppl=None,
      pl="宜蘭老屋一樓的花店，下雨天，門關著，她正在門上貼紙條",
      pl_en="at the front door of the flower shop on the ground floor of the old house in Yilan on a rainy day, the shop shut and a note going up on the glass",
      ac="她兩手把紙條按在門上，其中一隻手上有被刺傷的小傷口",
      ac_en="She is pressing the note flat against the door with both hands, one of them marked with a small thorn cut.",
      ac_s="小習慣：下雨天不營業，直接在門口貼紙條／手上常常有被刺傷的小傷口",
      wall_ok="門上那張她自己寫的紙條是場景的一部分，守則不得禁止它",
      of="米白色的棉質長洋裝，外面罩一件霧綠色的薄外套",
      of_en="an off-white cotton dress with a misty green light jacket over it",
      of_s="色盤：米白、霧綠",
      li="她站在門內側，雨天的灰白光從門外過來，店裡沒開燈所以她這一面暗",
      li_en="She is on the inside of the door with the grey-white rainy light coming from outside it, and with nothing switched on in the shop her own side is dark.",
      li_s="氛圍原句：「低飽和、霧面、潮濕。宜蘭的雨是她的固定配角」",
      fa="很淡，看著自己貼的那張紙",
      fa_en="Very mild, looking at the note she has just put up.",
      fa_s="語氣：貼文從來不超過十個字",
      hair_en="down and slightly damp from the rain"),
 dict(id="O2", ev="洗完澡上樓，濕頭髮還貼在鎖骨上",
      pil="浴室 / 晨間", wt="20%", flag=None, fam="浴室", pose="倚牆", hand="單手扶物",
      gaze="看鏡頭", view="selfie", topo="窗光側面", time="day", ppl=None,
      pl="老屋二樓的浴室，白天，舊磁磚，高窗的光從一側進來",
      pl_en="in the second-floor bathroom of the old house in the daytime, old tiles, light from a high window coming in from one side",
      ac="她靠著磁磚牆，一手撐在洗手台邊，濕頭髮貼在鎖骨上",
      ac_en="She is leaning against the tiled wall with one hand on the edge of the basin, her wet hair stuck to her collarbone.",
      ac_s="私下核心：剛洗完澡的濕髮貼在鎖骨上",
      of="白色的棉質吊帶上衣",
      of_en="a white cotton camisole",
      of_s="私下核心：白色棉質吊帶／色盤：米白",
      li="高窗的日光從一側進來，浴室另一側落暗，畫面允許過曝",
      li_en="Daylight from the high window comes in from one side, the other side of the room falls away, and the picture is allowed to blow out a little.",
      li_s="後製原句：「自然光為主，允許過曝與失焦」",
      fa="很輕，看著鏡頭",
      fa_en="Very light, looking at the lens.",
      fa_s="語氣：像自言自語被聽見了",
      hair_en="wet and stuck to her collarbone"),
 dict(id="O3", ev="雨天樓上把窗開著，那隻不知道誰的貓在地板上",
      pil="私下 / 老屋樓上", wt="25%", flag=None, fam="客廳", pose="坐地", hand="空手",
      gaze="看側邊", view="floor", topo="窗光側面", time="day", ppl=None,
      pl="老屋二樓的木地板房間，下雨天，窗開著，一隻貓趴在旁邊",
      pl_en="in the wooden-floored room on the second floor of the old house on a rainy day, the window open and a cat lying nearby",
      ac="她赤腳盤腿坐在木地板上，兩手擱在膝上看著貓",
      ac_en="She is sitting barefoot and cross-legged on the wooden floor, hands resting on her knees, watching the cat.",
      ac_s="小習慣：店裡永遠有一隻不知道誰的貓／私下核心：赤腳",
      of="淡粉色的棉質吊帶配寬鬆長褲",
      of_en="a pale pink cotton camisole with loose trousers",
      of_s="色盤：淡粉",
      li="雨天的窗光從側面進來，房間深處是灰的，對比很低",
      li_en="Rainy-day window light comes in from the side, the far side of the room goes grey, and the contrast is very low.",
      li_s="後製原句：「低對比、顆粒感」",
      fa="幾乎沒有表情，看著貓",
      fa_en="Almost no expression, watching the cat.",
      fa_s="幽默：幾乎沒有笑點",
      hair_en="down and air-drying"),
 dict(id="O4", ev="雨停了走去鎮上的雜貨店，屋簷下還有人在躲",
      pil="外出 / 小鎮", wt="15%", flag="房間以外", fam="老街", pose="站", hand="單手持物",
      gaze="看側邊", view="full", topo="單一光源側前", time="night",
      ppl=dict(level="1-2人", dist="中", act="也在屋簷下躲雨、跟店裡的人講話",
               wear="小鎮居民的日常衣服，雨鞋、薄外套", facing="背對鏡頭"),
      pl="宜蘭小鎮一間老雜貨店的屋簷下，雨剛停，地上還有水窪",
      pl_en="under the eaves of an old grocery shop in a small Yilan town just after the rain has stopped, puddles still on the ground",
      ac="她一手提著一小袋東西站在屋簷下，正要走出去",
      ac_en="She is standing under the eaves with a small bag in one hand, about to step out.",
      ac_s="誰是她：宜蘭",
      of="灰色的長版針織外套，裡面是米白的",
      of_en="a grey long knit cardigan over something off-white",
      of_s="色盤：灰、米白",
      li="雜貨店的燈從店裡打到屋簷下，街上暗，水窪把光反回來",
      li_en="Light from inside the shop reaches under the eaves, the street beyond is dark, and the puddles throw it back.",
      li_s="氛圍原句：「宜蘭的雨是她的固定配角」",
      fa="很安靜，看著街上",
      fa_en="Very quiet, looking out at the street.",
      fa_s="語氣：很輕、很短",
      hair_en="down and slightly damp"),
 dict(id="O5", ev="夜裡樓上只開一盞，她就這樣待著",
      pil="私下 / 老屋樓上", wt="25%", flag=None, fam="臥室", pose="半躺", hand="空手",
      gaze="閉眼", view="near", topo="單一光源側前", time="night", ppl=None,
      pl="老屋二樓她睡的房間，夜裡，只開了床邊那一盞",
      pl_en="in the room she sleeps in on the second floor of the old house at night, only the lamp by the bed switched on",
      ac="她赤腳蜷在床上，一隻手臂枕在頭下，另一隻攤在身前",
      ac_en="She is curled barefoot on the bed with one arm under her head and the other laid out in front of her.",
      ac_s="私下核心：她本來就這樣待在自己家裡",
      of="白色的棉質吊帶配同色短褲",
      of_en="a white cotton camisole with matching shorts",
      of_s="私下核心：白色棉質吊帶",
      li="床邊那一盞燈在她側前方很低，房間其餘部分暗，畫面保留顆粒",
      li_en="The lamp by the bed sits low and to one side of her, the rest of the room is dark, and the grain is left in the picture.",
      li_s="後製原句：「低對比、顆粒感」",
      fa="眼睛閉著，快睡著了",
      fa_en="Her eyes closed, almost asleep.",
      fa_s="語氣：像自言自語",
      hair_en="down and dry, spread on the pillow"),
])
